export const integrations = {
  // ── AI SDR Platforms ────────────────────────────────────────────
  "11x": {
    toolName: "11x",
    category: "AI SDR Platform",
    metaTitle: "Bookbag + 11x Compatibility | Bookbag Intelligence",
    metaDescription: "Route AI messages generated by 11x's Jessica agent through Bookbag's production gate. Catch hallucinations before they ship.",
    subtitle: "Bookbag is compatible with outbound messages generated by 11x's AI SDR agent, Jessica. Gate every AI-written email before it reaches your prospects.",
    description: "11x's Jessica agent writes outbound emails autonomously — no human drafting required. That's powerful, but it means no human sees the message before it ships. Bookbag adds the quality gate: every Jessica-generated email gets a verdict before it reaches your prospect.",
    compatibility: {
      channels: ["Email", "LinkedIn"],
      methods: ["CSV export", "API"],
    },
    howItWorks: [
      { title: "Jessica generates, Bookbag gates", description: "11x's Jessica agent produces email drafts autonomously. Before they enter your send queue, route them through Bookbag's AI Production Gate for verdict assignment." },
      { title: "Verdicts route the work", description: "safe_to_deploy emails ship automatically. needs_fix emails get QA corrections with gold-standard rewrites. blocked emails escalate to your SME with evidence and rationale." },
      { title: "Jessica gets smarter", description: "Export Bookbag corrections as SFT and DPO training pairs. Feed them back to improve Jessica's output quality over time — fewer flags, better first drafts." },
    ],
    benefits: [
      { title: "Jessica ships faster, not slower", description: "The majority of Jessica's emails pass review and are cleared for delivery through the gate. Only the ones that would have hurt your sender reputation hit the review queue." },
      { title: "Every correction trains Jessica", description: "Each needs_fix rewrite becomes a structured before/after pair. Export these as SFT data and feed them back into 11x — Jessica's first drafts get better every week." },
      { title: "Procurement gets the proof they need", description: "Enterprise buyers ask how you govern autonomous AI agents. Bookbag gives you timestamped, attributed verdicts for every Jessica email — audit-ready from day one." },
    ],
    faqs: [
      { question: "Does Bookbag have a native integration with 11x?", answer: "There's no native integration, but export and upload works well. You route Jessica's drafts to Bookbag via CSV export or API. Most teams set this up in under an hour." },
      { question: "How many Jessica emails can Bookbag handle?", answer: "As many as Jessica produces. Bookbag's AI Production Gate scales from hundreds to millions of messages per month. Safe emails are cleared for delivery quickly, so reviewer load stays manageable regardless of volume." },
      { question: "Will gating slow down Jessica's autonomous workflow?", answer: "The opposite — it speeds up the emails that matter. safe_to_deploy messages clear instantly. Only the ones Jessica got wrong hit the review queue, which means your prospects never see the bad ones." },
    ],
    relatedPersonas: ["ai-sdr-vendors", "revops"],
    relatedGlossary: ["ai-production-gate", "ai-hallucination-detection", "safe-to-deploy"],
    relatedComparison: "bookbag-vs-prompt-engineering",
    relatedIntegrations: ["artisan", "aisdr"],
  },

  "artisan": {
    toolName: "Artisan",
    category: "AI SDR Platform",
    metaTitle: "Bookbag + Artisan Compatibility | Bookbag Intelligence",
    metaDescription: "Gate AI outbound from Artisan's Ava agent through Bookbag. Add human-authority QA to every AI-generated sales email.",
    subtitle: "Bookbag is compatible with outbound messages generated by Artisan's AI sales agent, Ava. Add a quality gate between AI generation and prospect delivery.",
    description: "Artisan's Ava agent runs your entire top-of-funnel autonomously — research, personalization, sequencing. The tradeoff is that no human touches the message before it ships. Bookbag gives you the production gate that makes fully autonomous outbound safe to deploy at scale.",
    compatibility: {
      channels: ["Email", "LinkedIn"],
      methods: ["CSV export", "API"],
    },
    howItWorks: [
      { title: "Ava writes, Bookbag decides", description: "Ava produces personalized outbound at scale. Before those emails activate, route them through Bookbag's AI Production Gate. Each message gets a safe_to_deploy, needs_fix, or blocked verdict." },
      { title: "Fix and block lanes protect your domain", description: "needs_fix emails return with gold-standard rewrites — the exact correction Ava should have made. blocked emails escalate to your SME with rubric citations and reviewer rationale." },
      { title: "Ava improves from every correction", description: "Export correction pairs as structured SFT and DPO data. Feed them back to Artisan so Ava's personalization accuracy improves with every review cycle." },
    ],
    benefits: [
      { title: "Ava sends at volume, you send with confidence", description: "One bad batch from Ava can torch your domain reputation. Bookbag catches the risky messages before they hit inboxes — the majority of Ava's output passes review quickly, so throughput stays high." },
      { title: "Compliance proof for every Ava email", description: "Enterprise procurement asks how you govern AI agents. Bookbag provides a timestamped, attributed verdict for every Ava-generated email — reviewer identity, rubric citations, and evidence." },
      { title: "Ava's personalization gets sharper", description: "Every needs_fix correction is a structured before/after training pair. Export these to Artisan, and Ava writes better first drafts next quarter." },
    ],
    faqs: [
      { question: "Is there a native Bookbag-Artisan integration?", answer: "There's no native integration, but export and upload works well. You route Ava's drafts to Bookbag via CSV export or API — most teams are live in under an hour." },
      { question: "Does Bookbag replace Artisan's built-in quality checks?", answer: "No. Bookbag is an independent human-authority layer on top of whatever Artisan provides internally. Think of it as a production gate between Ava and your prospect's inbox." },
      { question: "What if Ava references the wrong company details?", answer: "That's exactly what the gate catches. Bookbag reviewers flag hallucinated facts, wrong company data, and inaccurate claims. Those corrections become SFT training pairs that reduce Ava's error rate over time." },
    ],
    relatedPersonas: ["ai-sdr-vendors", "head-of-cs"],
    relatedGlossary: ["ai-hallucination-detection", "gold-standard-rewrites", "ai-message-quality"],
    relatedComparison: "bookbag-vs-internal-qa",
    relatedIntegrations: ["11x", "aisdr"],
  },

  "aisdr": {
    toolName: "AiSDR",
    category: "AI SDR Platform",
    metaTitle: "Bookbag + AiSDR Compatibility | Bookbag Intelligence",
    metaDescription: "Route AiSDR-generated outbound through Bookbag's production gate. Add human review to AI sales emails before they send.",
    subtitle: "Bookbag is compatible with messages generated by AiSDR. Gate AI-written sales emails through human-authority review before they reach prospects.",
    description: "AiSDR automates prospect research and generates tailored outbound designed to book meetings. The risk: AI-personalized emails ship without a human verifying the facts. Bookbag sits between AiSDR and your send queue, giving every message a verdict before it reaches the prospect.",
    compatibility: {
      channels: ["Email", "LinkedIn"],
      methods: ["CSV export", "API"],
    },
    howItWorks: [
      { title: "AiSDR drafts, Bookbag verdicts", description: "AiSDR generates personalized outbound at scale. Before those messages enter your sending queue, route them through Bookbag's AI Production Gate for safe_to_deploy, needs_fix, or blocked verdict assignment." },
      { title: "Corrections come back production-ready", description: "needs_fix messages return with gold-standard rewrites — the exact email AiSDR should have written. blocked messages escalate to your SME with rubric citations and evidence." },
      { title: "AiSDR learns from every flag", description: "Export correction pairs as SFT and DPO training data. Feed them back into AiSDR's personalization engine so first-draft quality improves continuously." },
    ],
    benefits: [
      { title: "AiSDR's speed without the quality tradeoff", description: "AiSDR generates outbound fast. Bookbag ensures that speed doesn't cost you accuracy or brand safety — the majority of messages pass review quickly, so throughput barely changes." },
      { title: "Every AiSDR correction builds training data", description: "Each needs_fix rewrite is a structured before/after pair. Export these to improve AiSDR's personalization quality over time — fewer flags, better first drafts." },
      { title: "Enterprise audit trail for AiSDR output", description: "Regulated industries and enterprise procurement need proof that a human reviewed the AI's work. Bookbag provides timestamped, attributed verdicts for every AiSDR message." },
    ],
    faqs: [
      { question: "Can Bookbag handle AiSDR's output volume?", answer: "Yes. safe_to_deploy messages are cleared for delivery quickly, and only flagged items require human review. As rubrics get calibrated, reviewer throughput improves and reviewer load stays low regardless of AiSDR's volume." },
      { question: "Does this work with AiSDR's LinkedIn messaging?", answer: "Yes. Bookbag gates any text-based AI output — emails, LinkedIn messages, SMS. Route any AiSDR-generated content through the AI Production Gate regardless of channel." },
      { question: "How do I connect AiSDR to Bookbag?", answer: "Export AiSDR messages via CSV or API and submit them to Bookbag. No native plugin yet, but most teams are live in under an hour. The workflow is CSV export or API-based message transfer." },
    ],
    relatedPersonas: ["ai-sdr-vendors", "vp-product"],
    relatedGlossary: ["ai-production-gate", "sft-export", "needs-fix"],
    relatedComparison: "bookbag-vs-prompt-engineering",
    relatedIntegrations: ["11x", "artisan"],
  },

  "regie-ai": {
    toolName: "Regie.ai",
    category: "AI SDR Platform",
    metaTitle: "Bookbag + Regie.ai Compatibility | Bookbag Intelligence",
    metaDescription: "Add a production gate to Regie.ai-generated sales content. Route AI sequences through Bookbag for human-authority review.",
    subtitle: "Bookbag is compatible with AI-generated sales content from Regie.ai. Add human-authority quality gating to your AI engagement workflows.",
    description: "Regie.ai generates entire multi-step outbound sequences — not just single emails. That means one bad prompt can produce a five-touch sequence with compounding quality issues. Bookbag gates every step before activation, catching tone escalation, hallucinations, and compliance drift across the full sequence.",
    compatibility: {
      channels: ["Email", "LinkedIn"],
      methods: ["CSV export", "API"],
    },
    howItWorks: [
      { title: "Regie.ai builds the sequence, Bookbag reviews it", description: "Regie.ai generates multi-step outbound sequences. Before activating them in your engagement platform, route each step through Bookbag's AI Production Gate for verdict assignment." },
      { title: "Step-by-step and sequence-level verdicts", description: "Each step gets a safe_to_deploy, needs_fix, or blocked verdict. Bookbag also flags sequence-level problems — tone escalation between steps, repetitive messaging, or cumulative compliance risk." },
      { title: "Corrections refine Regie.ai's prompts", description: "Every needs_fix rewrite includes rubric citations and reviewer rationale. Use these to adjust Regie.ai's prompts and templates — each review cycle produces tighter first drafts." },
    ],
    benefits: [
      { title: "Sequence-level quality Regie.ai can't do alone", description: "Regie.ai optimizes individual emails. Bookbag reviews the full sequence arc — catching tone escalation from step 2 to step 5, repetitive ask patterns, and cumulative compliance risk." },
      { title: "Regie.ai campaigns protect your domains", description: "AI-generated sequences at scale can trigger spam signals. Bookbag catches aggressive language and risky patterns before they damage your sending domains or deliverability score." },
      { title: "Every correction makes Regie.ai sharper", description: "Export needs_fix rewrites as SFT and DPO pairs. Feed them back to refine Regie.ai's content generation — fewer flags and better first-draft sequences over time." },
    ],
    faqs: [
      { question: "Does Bookbag integrate directly with Regie.ai?", answer: "There's no native integration, but export and upload works well. Export Regie.ai sequence steps and route them through Bookbag via CSV export or API. Most teams are live within an hour." },
      { question: "Can Bookbag review an entire Regie.ai sequence at once?", answer: "Yes. Submit the full multi-step sequence. Bookbag evaluates each step individually and flags sequence-level issues like tone escalation, repetitive messaging, and inconsistent value propositions across steps." },
      { question: "How does this improve Regie.ai's output over time?", answer: "Every correction generates a structured before/after pair with rubric citations. Export these as training data to refine Regie.ai's prompts and templates — a feedback loop that compounds quality improvements." },
    ],
    relatedPersonas: ["sequencing-platforms", "sales-enablement"],
    relatedGlossary: ["ai-message-quality", "gold-standard-rewrites", "rubric-versioning"],
    relatedComparison: "rewrite-workflow-vs-prompt-tweaks",
    relatedIntegrations: ["salesforge", "jason-ai"],
  },

  "salesforge": {
    toolName: "Salesforge",
    category: "AI SDR Platform",
    metaTitle: "Bookbag + Salesforge Compatibility | Bookbag Intelligence",
    metaDescription: "Gate Salesforge AI-personalized emails through Bookbag before sending. Ensure every AI email meets quality and compliance standards.",
    subtitle: "Bookbag is compatible with AI-personalized emails from Salesforge. Route AI outputs through human-authority review before they reach prospects.",
    description: "Salesforge generates unique, personalized cold emails and pushes them through its own sending infrastructure. That's AI writing and AI sending in one pipeline — with no human checkpoint in between. Bookbag adds the AI Production Gate between Salesforge's personalization engine and your send queue, so every email gets a verdict before it touches a prospect.",
    compatibility: {
      channels: ["Email"],
      methods: ["CSV export", "API"],
    },
    howItWorks: [
      { title: "Salesforge personalizes, Bookbag verifies", description: "Salesforge generates unique personalized emails for each prospect. Before those emails enter Salesforge's sending queue, route them through Bookbag's AI Production Gate for safe_to_deploy, needs_fix, or blocked verdicts." },
      { title: "Corrections come back send-ready", description: "needs_fix emails return with gold-standard rewrites that match your brand voice and fix the specific issue. blocked emails escalate to your SME with rubric citations and evidence." },
      { title: "Salesforge personalization improves", description: "Export Bookbag corrections as SFT and DPO training pairs. Feed them back to improve Salesforge's personalization accuracy — fewer wrong company details, better tone calibration." },
    ],
    benefits: [
      { title: "Salesforge personalizes accurately, not just quickly", description: "AI personalization can reference wrong prospect details or fabricate company facts. Bookbag catches these before they become embarrassing outreach that damages your credibility." },
      { title: "Volume scales, risk doesn't", description: "Salesforge is built for high-volume sending. Bookbag ensures scaling AI personalization doesn't mean scaling quality risk — the majority of messages pass review, and the rest get thorough human attention." },
      { title: "Salesforge domains stay healthy", description: "Spammy AI content damages sender reputation. Bookbag flags aggressive language, excessive claims, and spam-trigger patterns before they touch Salesforge's sending infrastructure." },
    ],
    faqs: [
      { question: "How do I route Salesforge emails through Bookbag?", answer: "Export AI-generated drafts from Salesforge via CSV or API, submit them to Bookbag for verdicts, and import approved messages back into Salesforge for sending. Most teams are live in under an hour." },
      { question: "Does this add latency to my Salesforge campaigns?", answer: "Barely. safe_to_deploy messages clear instantly. Only needs_fix and blocked items require human review time. After rubric calibration, most messages pass review quickly so throughput stays high." },
      { question: "Can Bookbag handle Salesforge's multi-language output?", answer: "Yes. Configure rubrics per language so quality standards hold across international campaigns. Bookbag reviewers evaluate the final message as the prospect would see it, regardless of language." },
    ],
    relatedPersonas: ["cold-email-infrastructure", "revops"],
    relatedGlossary: ["outbound-deliverability-risk", "ai-brand-safety", "safe-to-deploy"],
    relatedComparison: "quality-gate-vs-deliverability-tooling",
    relatedIntegrations: ["regie-ai", "instantly"],
  },

  "jason-ai": {
    toolName: "Jason AI",
    category: "AI SDR Platform",
    metaTitle: "Bookbag + Jason AI Compatibility | Bookbag Intelligence",
    metaDescription: "Route Jason AI outbound messages through Bookbag's production gate. Add human-authority review to Reply.io's AI SDR.",
    subtitle: "Bookbag is compatible with outbound messages from Jason AI, Reply.io's AI SDR assistant. Gate AI-generated emails before they reach prospects.",
    description: "Jason AI lives inside Reply.io and does something most AI SDRs don't: it responds to prospect replies autonomously. That's powerful for speed, but it means an AI is having live conversations with your buyers without a human in the loop. Bookbag gates both Jason AI's initial outbound and its auto-responses before they ship.",
    compatibility: {
      channels: ["Email", "LinkedIn"],
      methods: ["CSV export", "API"],
    },
    howItWorks: [
      { title: "Jason AI writes, Bookbag reviews", description: "Jason AI generates outbound emails and auto-responses inside Reply.io. Before those messages send, route them through Bookbag's AI Production Gate for safe_to_deploy, needs_fix, or blocked verdicts." },
      { title: "Auto-responses get the same gate", description: "Jason AI's autonomous prospect replies are the highest-risk messages in your pipeline. Bookbag reviews them with the same rubric rigor as initial outbound — needs_fix responses get gold-standard rewrites." },
      { title: "Jason AI's replies improve over time", description: "Export correction pairs as SFT and DPO training data. Feed them back to improve both Jason AI's initial outbound and its auto-response quality." },
    ],
    benefits: [
      { title: "Jason AI's auto-responses don't go rogue", description: "Autonomous prospect replies are high-stakes. Bookbag ensures every Jason AI response meets your standards before it reaches a buyer who's already engaged." },
      { title: "Reply.io campaigns ship safely at volume", description: "High-volume Reply.io campaigns powered by Jason AI carry deliverability risk. Bookbag catches the messages that would damage your sender domains — the majority of messages pass review quickly, so throughput stays high." },
      { title: "Jason AI gets better every cycle", description: "Every needs_fix correction becomes a structured before/after pair. Export these to improve Jason AI's personalization and response quality in future Reply.io campaigns." },
    ],
    faqs: [
      { question: "Does Bookbag connect directly to Reply.io?", answer: "There's no native integration, but export and upload works well. Route Jason AI's drafts and auto-responses to Bookbag via CSV export or API. Most teams are live in under an hour." },
      { question: "Can Bookbag review Jason AI's auto-responses to prospects?", answer: "Yes — and you should. Auto-responses are the highest-risk AI messages in your pipeline because a prospect is already engaged. Bookbag gates them with the same rubric rigor as initial outbound." },
      { question: "Will this slow down my Reply.io sequences?", answer: "safe_to_deploy messages clear instantly. Only needs_fix and blocked items require human review. After rubric calibration, most of Jason AI's output passes review quickly." },
    ],
    relatedPersonas: ["ai-sdr-vendors", "sales-enablement"],
    relatedGlossary: ["message-gating", "needs-fix", "annotator-calibration"],
    relatedComparison: "bookbag-vs-prompt-engineering",
    relatedIntegrations: ["regie-ai", "apollo"],
  },

  // ── Sequencing Platforms ────────────────────────────────────────
  "apollo": {
    toolName: "Apollo",
    category: "Sequencing Platform",
    metaTitle: "Bookbag + Apollo Compatibility | Bookbag Intelligence",
    metaDescription: "Gate AI-generated Apollo sequences through Bookbag. Add human-authority QA before AI emails reach your prospects.",
    subtitle: "Bookbag is compatible with AI-generated sequences and emails from Apollo. Add a production gate to your Apollo outbound workflow.",
    description: "Apollo combines a massive B2B contact database with AI-powered email generation and sequencing. That means AI is writing personalized messages using Apollo's own prospect data — and if the AI misinterprets that data, the mistake goes out at scale. Bookbag gates Apollo's AI-generated sequences before activation, catching hallucinated facts and data misuse.",
    compatibility: {
      channels: ["Email", "LinkedIn", "Phone script"],
      methods: ["CSV export", "API"],
    },
    howItWorks: [
      { title: "Apollo generates, Bookbag gates before activation", description: "Pull AI-generated email sequences, one-off messages, and phone scripts from Apollo. Route them through Bookbag's AI Production Gate before activating in your Apollo sequences." },
      { title: "Verdicts catch what Apollo's data can't", description: "Each message gets a safe_to_deploy, needs_fix, or blocked verdict. Bookbag evaluates whether Apollo's AI correctly used the prospect data — wrong titles, outdated companies, and fabricated context get flagged." },
      { title: "Corrections improve Apollo's AI output", description: "Export needs_fix rewrites as SFT and DPO training pairs. Feed them back to improve how Apollo's AI uses its own data — fewer hallucinations, better personalization accuracy." },
    ],
    benefits: [
      { title: "Apollo's data is only as good as the AI using it", description: "Apollo provides rich contact and company data, but AI can misinterpret or hallucinate on top of it. Bookbag catches the gap between what the data says and what the AI writes." },
      { title: "Scale Apollo sequences safely", description: "Apollo's AI generates messages fast. Bookbag ensures scaling AI-generated outbound doesn't mean scaling quality risk — the majority of messages pass review, and the rest get human attention before activation." },
      { title: "Every Apollo correction is training data", description: "Each needs_fix rewrite becomes a structured before/after pair. Export these to improve future Apollo AI sequence quality — the feedback loop compounds over time." },
    ],
    faqs: [
      { question: "Does Bookbag have a native Apollo integration?", answer: "There's no native integration, but export and upload works well. Export Apollo's AI-generated content via CSV or API and route it through Bookbag. Most teams are live within an hour." },
      { question: "Can I gate Apollo sequences before they go live?", answer: "Yes. Export draft sequences from Apollo, run every step through Bookbag's AI Production Gate, and activate only the versions that received safe_to_deploy or corrected needs_fix verdicts." },
      { question: "Does this work with Apollo's AI email writer and phone scripts?", answer: "Yes. Any AI-generated text from Apollo — emails, subject lines, sequence steps, and call scripts — can be routed through Bookbag for verdict assignment." },
    ],
    relatedPersonas: ["sequencing-platforms", "revops"],
    relatedGlossary: ["ai-production-gate", "safe-to-deploy", "qa-review-workflow"],
    relatedComparison: "bookbag-vs-internal-qa",
    relatedIntegrations: ["salesloft", "outreach"],
  },

  "salesloft": {
    toolName: "Salesloft",
    category: "Sequencing Platform",
    metaTitle: "Bookbag + Salesloft Compatibility | Bookbag Intelligence",
    metaDescription: "Add a production gate to AI-generated Salesloft cadences. Route AI emails through Bookbag for human-authority review.",
    subtitle: "Bookbag is compatible with AI-generated cadence content from Salesloft. Gate AI emails and sequence steps through human-authority review.",
    description: "Salesloft cadences are the backbone of enterprise outbound. As Salesloft adds more AI features for message generation and refinement, the gap between what AI writes and what your brand should say widens. Bookbag gates every AI-generated cadence step before reps execute it — so your team sends with confidence, not fingers crossed.",
    compatibility: {
      channels: ["Email", "LinkedIn", "Phone script"],
      methods: ["CSV export", "API"],
    },
    howItWorks: [
      { title: "Salesloft generates cadences, Bookbag reviews them", description: "Export AI-generated email steps, LinkedIn touches, and call scripts from Salesloft cadences. Route them through Bookbag's AI Production Gate before reps begin executing." },
      { title: "Each step gets a verdict", description: "safe_to_deploy steps activate immediately. needs_fix steps return with gold-standard rewrites. blocked steps escalate to your SME. Bookbag also flags cadence-level issues — tone escalation, repetitive asks, compliance drift across steps." },
      { title: "Salesloft cadences tighten over time", description: "Export correction data as SFT and DPO pairs. Use these to refine Salesloft's AI-generated cadence templates — each review cycle produces better first-draft cadences." },
    ],
    benefits: [
      { title: "Reps trust Salesloft cadences because Bookbag reviewed them", description: "Sales reps hesitate to execute AI-generated cadences they haven't read. When every step has a Bookbag verdict, reps send confidently — adoption goes up, not down." },
      { title: "Cadence-level quality that Salesloft can't do alone", description: "Salesloft AI optimizes individual steps. Bookbag reviews the full cadence arc — catching tone escalation from step 1 to step 5, contradictions between touches, and cumulative compliance risk." },
      { title: "Governance that unlocks Salesloft AI adoption", description: "Enterprise buyers ask how you govern AI-assisted outreach. Bookbag gives you the documented, auditable governance layer that procurement requires before approving Salesloft's AI features." },
    ],
    faqs: [
      { question: "Does Bookbag integrate directly with Salesloft?", answer: "There's no native integration, but export and upload works well. Export AI-generated cadence content via CSV or API and route it through Bookbag. Most teams are live within an hour." },
      { question: "Can Bookbag review Salesloft AI-generated subject lines and call scripts?", answer: "Yes. Bookbag gates any text-based AI output from Salesloft — subject lines, email bodies, LinkedIn messages, and call scripts all receive verdicts." },
      { question: "How do I get started with Salesloft and Bookbag?", answer: "Export a sample cadence from Salesloft, submit it to Bookbag, and see verdicts within your SLA window. Most teams pilot with one cadence before scaling to all AI-generated content." },
    ],
    relatedPersonas: ["sequencing-platforms", "sales-enablement"],
    relatedGlossary: ["message-gating", "rubric-versioning", "gold-standard-rewrites"],
    relatedComparison: "bookbag-vs-manual-review",
    relatedIntegrations: ["outreach", "apollo"],
  },

  "outreach": {
    toolName: "Outreach",
    category: "Sequencing Platform",
    metaTitle: "Bookbag + Outreach Compatibility | Bookbag Intelligence",
    metaDescription: "Route AI-generated Outreach sequences through Bookbag's production gate. Add human-authority review to AI sales emails.",
    subtitle: "Bookbag is compatible with AI-generated content from Outreach. Add a quality gate to AI-powered sequences before they reach prospects.",
    description: "Outreach is the sales execution platform enterprise revenue teams rely on for sequences, multi-channel engagement, and pipeline management. As Outreach layers in more AI for email generation, the stakes are high — your biggest deals run through these sequences. Bookbag gates every AI-generated touchpoint before it reaches a decision-maker.",
    compatibility: {
      channels: ["Email", "LinkedIn", "Phone script"],
      methods: ["CSV export", "API"],
    },
    howItWorks: [
      { title: "Outreach AI generates, Bookbag gates before execution", description: "Export AI-generated sequence emails, templates, and Smart Email Assist outputs from Outreach. Route them through Bookbag's AI Production Gate before activating sequences." },
      { title: "Verdicts protect your highest-value touches", description: "Each message gets a safe_to_deploy, needs_fix, or blocked verdict. needs_fix messages return with gold-standard rewrites. blocked messages escalate to your SME with rubric citations." },
      { title: "Outreach AI quality compounds over time", description: "Export correction pairs as SFT and DPO data. Feed them back to improve Outreach's AI content generation — each cycle produces better first-draft sequences." },
    ],
    benefits: [
      { title: "Enterprise accounts deserve reviewed touchpoints", description: "Outreach sequences targeting strategic accounts cannot afford AI errors. Bookbag ensures every touchpoint is reviewed before it reaches a key decision-maker — the cost of one bad email is too high." },
      { title: "Governance that unlocks Outreach AI adoption", description: "Enterprise procurement teams need proof you govern AI-assisted outreach. Bookbag provides timestamped, attributed verdicts for every Outreach AI message — the governance layer that gets AI approved." },
      { title: "Outreach sequences improve with every correction", description: "Corrections build a library of approved messaging patterns. Export these to improve Outreach AI sequence quality and train reps on what good enterprise outbound looks like." },
    ],
    faqs: [
      { question: "Is there a native Bookbag-Outreach integration?", answer: "There's no native integration, but export and upload works well. Export Outreach AI content via CSV or API and route it through Bookbag. Most teams are live within an hour." },
      { question: "Can Bookbag handle Outreach's volume?", answer: "Yes. safe_to_deploy messages are cleared for delivery quickly. Only needs_fix and blocked items require human review. After rubric calibration, the majority of Outreach AI output passes review without issue." },
      { question: "Does this work with Outreach's Smart Email Assist?", answer: "Yes. Any AI-generated text from Outreach — Smart Email Assist, AI-generated templates, sequence steps, and call scripts — can be routed through Bookbag for verdict assignment." },
    ],
    relatedPersonas: ["sequencing-platforms", "revops"],
    relatedGlossary: ["ai-production-gate", "ai-audit-trail", "safe-to-deploy"],
    relatedComparison: "bookbag-vs-internal-qa",
    relatedIntegrations: ["salesloft", "apollo"],
  },

  "hubspot-sales-hub": {
    toolName: "HubSpot Sales Hub",
    category: "Sequencing Platform",
    metaTitle: "Bookbag + HubSpot Sales Hub | Bookbag Intelligence",
    metaDescription: "Gate AI-generated HubSpot Sales Hub emails through Bookbag. Add human review to AI sequences before they reach contacts.",
    subtitle: "Bookbag is compatible with AI-generated content from HubSpot Sales Hub. Route AI emails and sequence content through human-authority review.",
    description: "HubSpot Sales Hub is where most SMB and mid-market sales teams live — CRM, sequencing, and pipeline all in one place. As HubSpot adds AI content generation, the AI is writing emails using your CRM data. If it misinterprets a contact field or hallucinates a company detail, the error ships from your CRM directly to your prospect. Bookbag gates HubSpot's AI-generated content before it leaves your sequences.",
    compatibility: {
      channels: ["Email", "LinkedIn", "Phone script"],
      methods: ["CSV export", "API"],
    },
    howItWorks: [
      { title: "HubSpot AI writes, Bookbag reviews before send", description: "Pull AI-generated email drafts, sequence steps, and templates from HubSpot Sales Hub. Route them through Bookbag's AI Production Gate before activating in your sequences." },
      { title: "CRM data usage gets verified", description: "Bookbag reviewers check whether HubSpot's AI correctly used your CRM data. safe_to_deploy messages activate immediately. needs_fix messages return with gold-standard rewrites. blocked messages escalate to your SME." },
      { title: "HubSpot AI quality improves from your data", description: "Export correction pairs as SFT and DPO training data. Use these to refine how HubSpot's AI uses your CRM data — fewer hallucinations, better personalization accuracy." },
    ],
    benefits: [
      { title: "HubSpot's CRM data is only useful if AI uses it correctly", description: "HubSpot centralizes your contact and company data. Bookbag catches cases where the AI misinterprets fields, hallucinates company details, or generates messages that don't match the CRM record." },
      { title: "Growing teams don't outgrow quality", description: "As your team scales AI usage in HubSpot, Bookbag prevents quality from degrading with volume. The AI Production Gate ensures every message meets your standards regardless of team size." },
      { title: "Every HubSpot correction is training data", description: "Corrections to HubSpot AI outputs become structured before/after pairs. Export these to improve AI content generation — the feedback loop compounds quality improvements over time." },
    ],
    faqs: [
      { question: "Does Bookbag integrate with HubSpot directly?", answer: "There's no native integration, but export and upload works well. Export HubSpot AI content via CSV or API and route it through Bookbag. Most teams are live within an hour." },
      { question: "Can I gate HubSpot's AI email writer outputs?", answer: "Yes. Any AI-generated content from HubSpot — the AI email writer, sequence suggestions, template generation, and subject line recommendations — can be routed through Bookbag for verdicts." },
      { question: "Is this relevant for HubSpot Marketing Hub too?", answer: "Bookbag focuses on outbound sales messaging. If your marketing team generates AI-powered outbound emails through HubSpot Marketing Hub, those can also be gated through the AI Production Gate." },
    ],
    relatedPersonas: ["b2b-saas", "sales-enablement"],
    relatedGlossary: ["ai-message-quality", "qa-review-workflow", "audit-ready-review"],
    relatedComparison: "bookbag-vs-manual-review",
    relatedIntegrations: ["salesloft", "outreach"],
  },

  // ── Cold Email Infrastructure ───────────────────────────────────
  "smartlead": {
    toolName: "Smartlead",
    category: "Cold Email Infrastructure",
    metaTitle: "Bookbag + Smartlead Compatibility | Bookbag Intelligence",
    metaDescription: "Route AI-generated cold emails through Bookbag before sending via Smartlead. Protect deliverability with human-authority QA.",
    subtitle: "Bookbag is compatible with cold email content sent through Smartlead. Gate AI-generated messages before they enter Smartlead's sending infrastructure.",
    description: "Smartlead handles the hard part of cold email infrastructure — mailbox rotation, warm-up, deliverability tuning. You spend weeks warming up domains. One batch of spammy AI-generated content can undo all of it. Bookbag sits between your AI copy and Smartlead's sending queue, ensuring only reviewed emails touch your warmed-up infrastructure.",
    compatibility: {
      channels: ["Email"],
      methods: ["CSV export", "API"],
    },
    howItWorks: [
      { title: "Gate before Smartlead import", description: "Before loading AI-generated email content into Smartlead campaigns, route it through Bookbag's AI Production Gate. Only emails with verdicts enter your sending infrastructure." },
      { title: "Spam triggers and compliance get caught", description: "Each email gets a safe_to_deploy, needs_fix, or blocked verdict. Bookbag catches spam-trigger language, compliance violations, aggressive tone, and factual errors before they touch your warmed-up domains." },
      { title: "Only clean content reaches Smartlead", description: "safe_to_deploy emails import directly. needs_fix emails return with gold-standard rewrites. blocked emails escalate to your SME. Your Smartlead warm-up investment stays protected." },
    ],
    benefits: [
      { title: "Weeks of Smartlead warm-up don't get burned by bad AI copy", description: "Smartlead's domain warm-up and mailbox rotation are investments. One batch of spammy AI content can undo weeks of work. Bookbag prevents this by catching deliverability risks before import." },
      { title: "Volume amplifies problems — Bookbag catches them first", description: "High-volume cold email amplifies every quality issue across thousands of sends. Bookbag catches spam triggers, excessive claims, and risky formatting before they scale through Smartlead." },
      { title: "Smartlead campaigns stay compliant at scale", description: "Bookbag reviewers flag CAN-SPAM issues, aggressive language, and misleading claims. Your Smartlead campaigns ship compliant regardless of how fast your AI generates copy." },
    ],
    faqs: [
      { question: "Does Bookbag integrate with Smartlead's API?", answer: "Not natively yet. Route AI-generated content through Bookbag via CSV export or API, then import approved emails into Smartlead. Most teams set this up in under an hour." },
      { question: "How does this protect my Smartlead warm-up investment?", answer: "Bookbag catches spammy language, compliance violations, and aggressive tone before emails enter Smartlead's sending queue. Your warmed-up domains and mailbox reputation stay clean." },
      { question: "Can Bookbag review all my Smartlead campaign variants?", answer: "Yes. Submit all variants and A/B test versions. Each variant receives an independent safe_to_deploy, needs_fix, or blocked verdict, so you know exactly which versions are safe to send." },
    ],
    relatedPersonas: ["cold-email-infrastructure", "deliverability-agencies"],
    relatedGlossary: ["outbound-deliverability-risk", "message-gating", "safe-to-deploy"],
    relatedComparison: "quality-gate-vs-deliverability-tooling",
    relatedIntegrations: ["instantly", "lemlist"],
  },

  "instantly": {
    toolName: "Instantly",
    category: "Cold Email Infrastructure",
    metaTitle: "Bookbag + Instantly Compatibility | Bookbag Intelligence",
    metaDescription: "Gate AI cold emails before sending through Instantly. Protect your domains with Bookbag's human-authority production gate.",
    subtitle: "Bookbag is compatible with cold email content sent through Instantly. Review AI-generated messages before they enter Instantly's sending infrastructure.",
    description: "Instantly is built for scale — domain rotation, mailbox warm-up, campaign management, all optimized for high-volume cold outbound. But Instantly optimizes delivery, not content quality. If AI generates spammy copy or hallucinated claims, Instantly sends them fast across all your domains. Bookbag gates the content before it enters Instantly, protecting the infrastructure you built.",
    compatibility: {
      channels: ["Email"],
      methods: ["CSV export", "API"],
    },
    howItWorks: [
      { title: "Gate AI content before Instantly import", description: "Route AI-generated email copy through Bookbag's AI Production Gate before importing it into Instantly campaigns. Each email gets a safe_to_deploy, needs_fix, or blocked verdict." },
      { title: "Deliverability risks get caught at the gate", description: "Bookbag catches spam-trigger language, compliance violations, factual errors, and aggressive tone. needs_fix emails return with gold-standard rewrites. blocked emails escalate to your SME." },
      { title: "Only clean content enters Instantly", description: "safe_to_deploy emails import directly into Instantly. Your domain reputation and warm-up investment stay protected because only reviewed content touches your sending infrastructure." },
    ],
    benefits: [
      { title: "Instantly sends fast — Bookbag makes sure it sends safe", description: "You invested heavily in Instantly's domain and mailbox setup. Bookbag prevents AI-generated content from burning those assets with spammy, non-compliant, or hallucinated messages." },
      { title: "Scale volume without scaling risk", description: "Instantly enables high-volume sending. Bookbag ensures that scaling from 1,000 to 100,000 sends doesn't mean scaling deliverability-damaging content across all your domains." },
      { title: "CAN-SPAM compliance at Instantly's volume", description: "Cold email at Instantly's scale requires careful compliance management. Bookbag catches CAN-SPAM issues, misleading claims, and regulatory risks before they ship to thousands of recipients." },
    ],
    faqs: [
      { question: "How do I use Bookbag with Instantly?", answer: "Generate AI email content, route it through Bookbag via CSV export or API, and import approved messages into Instantly. The pre-send workflow takes under an hour to set up and doesn't change your Instantly configuration." },
      { question: "Does Bookbag catch spam triggers before Instantly sends them?", answer: "Yes. Bookbag reviewers flag language patterns, formatting issues, and content that commonly triggers spam filters. This is exactly the kind of check you need before Instantly amplifies it across your domains." },
      { question: "Can I review AI-personalized messages for my Instantly lead lists?", answer: "Yes. Submit AI-personalized messages through Bookbag before importing them into Instantly campaigns. Each message receives an individual safe_to_deploy, needs_fix, or blocked verdict." },
    ],
    relatedPersonas: ["cold-email-infrastructure", "revops"],
    relatedGlossary: ["outbound-deliverability-risk", "can-spam-ai-messaging", "blocked-verdict"],
    relatedComparison: "quality-gate-vs-deliverability-tooling",
    relatedIntegrations: ["smartlead", "lemlist"],
  },

  "lemlist": {
    toolName: "Lemlist",
    category: "Cold Email Infrastructure",
    metaTitle: "Bookbag + Lemlist Compatibility | Bookbag Intelligence",
    metaDescription: "Route AI-personalized Lemlist campaigns through Bookbag before sending. Add human-authority QA to outbound at scale.",
    subtitle: "Bookbag is compatible with AI-generated outreach content from Lemlist. Gate personalized cold emails through human-authority review.",
    description: "Lemlist differentiates on creative personalization — dynamic images, custom landing pages, AI-powered content unique to each prospect. The risk is that creative personalization is harder to QA than plain text. When Lemlist's AI generates a unique email per prospect, who checks 10,000 unique messages? Bookbag does — every email gets a verdict before it launches.",
    compatibility: {
      channels: ["Email"],
      methods: ["CSV export", "API"],
    },
    howItWorks: [
      { title: "Lemlist personalizes, Bookbag verifies", description: "Lemlist generates unique AI-personalized emails and content per prospect. Before launching the campaign, route fully rendered messages through Bookbag's AI Production Gate." },
      { title: "Personalization errors get caught", description: "Each email gets a safe_to_deploy, needs_fix, or blocked verdict. Bookbag catches wrong company details, incorrect titles, fabricated facts, and personalization variables that rendered incorrectly." },
      { title: "Lemlist personalization quality compounds", description: "Export correction pairs as SFT and DPO training data. Feed them back to improve Lemlist's AI personalization — fewer hallucinated details, more accurate prospect references." },
    ],
    benefits: [
      { title: "Lemlist's creative personalization gets verified", description: "Lemlist generates unique content per prospect. Bookbag catches when personalization goes wrong — wrong company details, incorrect titles, fabricated facts — before your prospect sees the error." },
      { title: "Creative outreach meets brand standards", description: "Lemlist enables creative formats that are harder to QA at scale. Bookbag ensures AI-generated creative content meets your brand voice and quality standards across every variant." },
      { title: "Approved personalization patterns become reusable", description: "Corrections to Lemlist AI content build a library of approved personalization patterns. Use these as templates and training data for future campaigns — good patterns compound." },
    ],
    faqs: [
      { question: "Does Bookbag integrate directly with Lemlist?", answer: "There's no native integration, but export and upload works well. Export Lemlist content via CSV or API and route it through Bookbag before launching. Most teams set this up in under an hour." },
      { question: "Can Bookbag check Lemlist custom variables after rendering?", answer: "Yes. Submit fully rendered emails with all variables populated. Bookbag reviews the final message exactly as the prospect would see it, catching personalization data issues in context." },
      { question: "Does this work for Lemlist's LinkedIn and multi-channel outreach?", answer: "Yes. Bookbag gates any text-based outbound — emails, LinkedIn messages, and other channels generated through Lemlist's multi-channel campaigns all get verdicts." },
    ],
    relatedPersonas: ["cold-email-infrastructure", "b2b-saas"],
    relatedGlossary: ["ai-brand-safety", "gold-standard-rewrites", "ai-message-quality"],
    relatedComparison: "rewrite-workflow-vs-prompt-tweaks",
    relatedIntegrations: ["smartlead", "woodpecker"],
  },

  "woodpecker": {
    toolName: "Woodpecker",
    category: "Cold Email Infrastructure",
    metaTitle: "Bookbag + Woodpecker Compatibility | Bookbag Intelligence",
    metaDescription: "Gate AI-generated Woodpecker campaigns through Bookbag. Add human review to cold email before sending at scale.",
    subtitle: "Bookbag is compatible with cold email content sent through Woodpecker. Review AI-generated campaigns before they reach prospects.",
    description: "Woodpecker automates B2B cold email sequences with follow-up automation, deliverability monitoring, and A/B testing. The risk with AI-generated follow-ups: tone escalation. What starts as a professional first email can turn aggressive by follow-up three. Bookbag gates every email and follow-up in your Woodpecker campaigns, catching escalation before it damages your reputation.",
    compatibility: {
      channels: ["Email"],
      methods: ["CSV export", "API"],
    },
    howItWorks: [
      { title: "Gate before Woodpecker import", description: "Route AI-generated email content — initial sends and follow-ups — through Bookbag's AI Production Gate before importing into Woodpecker campaigns. Each email gets a verdict." },
      { title: "Follow-ups and A/B variants all get reviewed", description: "Each email and follow-up step gets a safe_to_deploy, needs_fix, or blocked verdict. Bookbag catches tone escalation across follow-ups and flags risky A/B variants independently." },
      { title: "Only approved content enters Woodpecker", description: "safe_to_deploy emails import directly. needs_fix emails return with gold-standard rewrites. blocked emails escalate to your SME. Your Woodpecker campaigns run with reviewed content only." },
    ],
    benefits: [
      { title: "Woodpecker follow-ups don't escalate into aggression", description: "Woodpecker automates follow-ups, and AI-generated follow-up sequences can drift toward aggressive or non-compliant messaging. Bookbag catches tone escalation before it reaches your prospect's inbox." },
      { title: "A/B test variants get independent verdicts", description: "Submit all A/B variants through Bookbag before testing. Each variant gets its own safe_to_deploy, needs_fix, or blocked verdict — no risky copy makes it into your test campaigns." },
      { title: "Agency clients get per-client quality standards", description: "Agencies managing multiple client campaigns in Woodpecker can configure independent rubrics per client. Every client's AI-generated content gets reviewed against their specific brand and compliance standards." },
    ],
    faqs: [
      { question: "How do I connect Bookbag with Woodpecker?", answer: "Export AI-generated email content and submit it to Bookbag via CSV or API. Import approved content into Woodpecker. No direct plugin yet, but most teams are live in under an hour." },
      { question: "Can Bookbag review Woodpecker follow-up sequences for tone escalation?", answer: "Yes. Submit the entire follow-up sequence. Bookbag evaluates each step individually and flags sequence-level issues — tone escalation, repetitive messaging, and cumulative compliance risk across follow-ups." },
      { question: "Does this work with Woodpecker's agency features?", answer: "Yes. Agencies route all AI-generated content through Bookbag with per-client rubric configurations. Each client's campaigns get reviewed against their specific brand, tone, and compliance standards." },
    ],
    relatedPersonas: ["cold-email-infrastructure", "deliverability-agencies"],
    relatedGlossary: ["can-spam-ai-messaging", "outbound-deliverability-risk", "needs-fix"],
    relatedComparison: "quality-gate-vs-deliverability-tooling",
    relatedIntegrations: ["lemlist", "smartlead"],
  },

  // ── Revenue Intelligence ────────────────────────────────────────
  "gong": {
    toolName: "Gong",
    category: "Intent & Enrichment",
    metaTitle: "Bookbag + Gong Compatibility | Bookbag Intelligence",
    metaDescription: "Use Gong conversation insights alongside Bookbag's production gate. Improve AI outbound quality with revenue intelligence data.",
    subtitle: "Bookbag works alongside Gong's conversation intelligence. Use call insights to inform outbound quality rubrics and improve AI-generated messaging.",
    description: "Gong records and analyzes every sales call, meeting, and email your team sends. It knows what messaging actually works with buyers. The problem: AI outbound tools don't have access to those insights. Bookbag bridges the gap — use Gong's conversation intelligence to build the rubrics that gate your AI-generated outbound.",
    compatibility: {
      channels: ["Email", "Phone script"],
      methods: ["CSV export"],
    },
    howItWorks: [
      { title: "Gong reveals what works, Bookbag enforces it", description: "Use Gong's conversation data to identify winning messaging patterns. Build Bookbag rubrics that enforce those patterns — so your AI Production Gate checks outbound against what actually converts." },
      { title: "Deal context gets verified before send", description: "When AI generates outbound referencing deal context or call outcomes, Bookbag reviewers verify those references against reality. Emails that misrepresent the conversation history get needs_fix or blocked verdicts." },
      { title: "Gong outcomes close the feedback loop", description: "Track which Bookbag-approved messages lead to Gong-recorded conversations. Use this data to continuously refine your rubrics — the quality bar moves based on real buyer response data." },
    ],
    benefits: [
      { title: "Rubrics built on Gong data, not guesswork", description: "Instead of guessing what good outbound looks like, use Gong's data on what actually resonates in buyer conversations to define your Bookbag quality standards. Evidence-based rubrics produce better verdicts." },
      { title: "AI outbound matches your best reps' messaging", description: "Gong shows which messaging patterns your top performers use. Bookbag rubrics enforce those patterns on AI-generated outbound — so every email aligns with what works, not what the AI defaults to." },
      { title: "Deal context stays accurate in AI emails", description: "AI messages that reference previous calls or deal status can hallucinate context. Bookbag catches claims that don't match the actual Gong-recorded conversation history." },
    ],
    faqs: [
      { question: "Does Bookbag pull data directly from Gong?", answer: "No. The workflow is: your team uses Gong insights to build Bookbag rubrics manually. Those rubrics then enforce proven messaging patterns on AI-generated outbound through the AI Production Gate." },
      { question: "How specifically do Gong insights improve Bookbag rubrics?", answer: "Gong reveals what messaging converts in real conversations — objection handling patterns, value prop framing, tone. Build rubrics that check AI outbound for those specific patterns. The result: your AI Production Gate is calibrated to real buyer data." },
      { question: "Can Bookbag review templates based on Gong recommendations?", answer: "Yes. If you use Gong's insights to generate AI email templates, route those templates through Bookbag before deploying them in sequences. Each template gets a safe_to_deploy, needs_fix, or blocked verdict." },
    ],
    relatedPersonas: ["revops", "sales-enablement"],
    relatedGlossary: ["rubric-versioning", "ai-message-quality", "annotator-calibration"],
    relatedComparison: "rewrite-workflow-vs-prompt-tweaks",
    relatedIntegrations: ["salesloft", "outreach"],
  },

  // ── Intent & Enrichment ─────────────────────────────────────────
  "6sense": {
    toolName: "6sense",
    category: "Intent & Enrichment",
    metaTitle: "Bookbag + 6sense Compatibility | Bookbag Intelligence",
    metaDescription: "Gate AI outbound triggered by 6sense intent signals through Bookbag. Ensure intent-driven messages are accurate and compliant.",
    subtitle: "Bookbag works alongside 6sense intent data. Gate AI-generated messages triggered by buying signals through human-authority review.",
    description: "6sense identifies your highest-intent accounts — the ones most likely to buy. These are the accounts where a bad AI email is most expensive. When AI generates outbound triggered by 6sense intent signals, Bookbag gates every message before it reaches a high-intent buyer, ensuring your best opportunities get your best messaging.",
    compatibility: {
      channels: ["Email", "LinkedIn"],
      methods: ["CSV export", "API"],
    },
    howItWorks: [
      { title: "6sense signals trigger AI outbound, Bookbag gates it", description: "When 6sense identifies in-market accounts, your team generates AI outbound targeting them. Before those messages send, route them through Bookbag's AI Production Gate for verdict assignment." },
      { title: "Intent claims get verified", description: "AI messages that reference buying signals, pain points, or account context get reviewed for accuracy. Emails that over-claim knowledge of the prospect's situation receive needs_fix or blocked verdicts." },
      { title: "High-intent accounts get reviewed messaging", description: "safe_to_deploy messages ship to high-intent accounts with confidence. Every message has a documented verdict — reviewer identity, rubric citations, and evidence." },
    ],
    benefits: [
      { title: "Your best opportunities get your best messaging", description: "6sense identified these accounts because they're ready to buy. A hallucinated claim or aggressive tone in the AI email wastes that signal. Bookbag prevents the mistake that costs you the deal." },
      { title: "AI doesn't over-claim knowledge of buyer intent", description: "AI may reference buying signals it doesn't actually have, or assume a buying stage beyond what 6sense data supports. Bookbag catches messaging that makes indefensible claims about the prospect's situation." },
      { title: "ABM quality holds at 6sense's scale", description: "Intent-driven ABM campaigns require personalized, high-quality messaging for every account. Bookbag ensures quality standards hold as 6sense surfaces more accounts and AI generates more outbound." },
    ],
    faqs: [
      { question: "Does Bookbag connect directly to 6sense?", answer: "No. The workflow is: 6sense identifies intent, your team generates AI outbound targeting those accounts, and Bookbag gates the messages via CSV export or API before delivery." },
      { question: "Can Bookbag verify whether AI accurately represents 6sense intent data?", answer: "Bookbag reviews the messaging, not the data source. Reviewers flag emails that make unsupported claims about the prospect's intent, buying stage, or needs — ensuring the AI doesn't over-extrapolate from the signal." },
      { question: "Does this work with 6sense orchestration workflows?", answer: "Yes. Any AI-generated messaging triggered by 6sense orchestration rules can be routed through Bookbag's AI Production Gate before reaching the recipient. The gate sits between AI generation and send." },
    ],
    relatedPersonas: ["revops", "b2b-saas"],
    relatedGlossary: ["ai-brand-safety", "ai-production-gate", "audit-ready-review"],
    relatedComparison: "bookbag-vs-prompt-engineering",
    relatedIntegrations: ["clearbit", "zoominfo"],
  },

  // ── Data Sources ────────────────────────────────────────────────
  "clearbit": {
    toolName: "Clearbit",
    category: "Data Source",
    metaTitle: "Bookbag + Clearbit Compatibility | Bookbag Intelligence",
    metaDescription: "Gate AI outbound enriched by Clearbit data through Bookbag. Ensure data-driven personalization is accurate before sending.",
    subtitle: "Bookbag works alongside Clearbit-enriched data. Gate AI messages that use enrichment data through human-authority review before delivery.",
    description: "Clearbit enriches your CRM with firmographic, technographic, and demographic data. You pay for that data so AI can write better personalized emails. But AI can misinterpret enrichment fields or hallucinate on top of them — referencing the wrong industry, fabricating a tech stack detail, or inventing a company attribute. Bookbag verifies that AI-generated messages actually use Clearbit data correctly.",
    compatibility: {
      channels: ["Email", "LinkedIn"],
      methods: ["CSV export", "API"],
    },
    howItWorks: [
      { title: "Clearbit enriches, AI writes, Bookbag verifies", description: "Clearbit provides the enrichment data. AI generates personalized outbound using it. Before those messages send, route them through Bookbag's AI Production Gate to verify data usage accuracy." },
      { title: "Data misuse gets flagged", description: "Bookbag reviewers check whether AI correctly referenced Clearbit data. Hallucinated company details, wrong industries, incorrect tech stack references, and fabricated attributes get needs_fix or blocked verdicts." },
      { title: "Corrections track which fields AI struggles with", description: "Every correction documents exactly what the AI got wrong. Track patterns over time — identify which Clearbit enrichment fields AI misinterprets most and adjust your prompts accordingly." },
    ],
    benefits: [
      { title: "Clearbit data is only valuable if AI uses it right", description: "You pay for Clearbit enrichment to improve personalization. Bookbag ensures AI actually uses that data correctly instead of generating plausible-sounding but inaccurate details that waste your investment." },
      { title: "AI hallucinations on enrichment data get caught", description: "AI sometimes misinterprets or fabricates on top of Clearbit data — wrong industry classifications, incorrect revenue ranges, invented technographic details. Bookbag catches these before your prospect sees them." },
      { title: "Error patterns reveal prompt improvements", description: "When Bookbag flags data misuse, patterns emerge. Identify which Clearbit enrichment fields AI struggles with most and adjust your prompts or templates — the error rate drops with each cycle." },
    ],
    faqs: [
      { question: "Does Bookbag use Clearbit data directly?", answer: "No. Bookbag reviews the AI-generated message, not the underlying data source. Reviewers flag messages where the AI appears to have misused enrichment data or fabricated details beyond what Clearbit provided." },
      { question: "Can Bookbag catch when AI ignores Clearbit data entirely?", answer: "Yes. If AI generates generic messaging instead of using available Clearbit enrichment, reviewers can flag this as a personalization quality issue based on your rubric criteria — you paid for the data, the AI should use it." },
      { question: "Does this work if we use Clearbit with HubSpot?", answer: "Yes. Regardless of where Clearbit data feeds into your stack — HubSpot, Salesforce, or a custom pipeline — any AI-generated outbound referencing enrichment data can be routed through Bookbag for review." },
    ],
    relatedPersonas: ["b2b-saas", "revops"],
    relatedGlossary: ["ai-hallucination-detection", "ai-message-quality", "taxonomy-config"],
    relatedComparison: "bookbag-vs-prompt-engineering",
    relatedIntegrations: ["zoominfo", "6sense"],
  },

  "zoominfo": {
    toolName: "ZoomInfo",
    category: "Data Source",
    metaTitle: "Bookbag + ZoomInfo Compatibility | Bookbag Intelligence",
    metaDescription: "Gate AI outbound powered by ZoomInfo data through Bookbag. Verify AI personalization accuracy before sending.",
    subtitle: "Bookbag works alongside ZoomInfo contact and company data. Gate AI-generated messages that use ZoomInfo data through human-authority review.",
    description: "ZoomInfo provides the contact and company data that powers your AI outbound — titles, departments, tech stacks, revenue ranges. The issue: AI can misinterpret this data, reference outdated information, or hallucinate details ZoomInfo never provided. Bookbag catches the gap between what ZoomInfo says and what your AI writes, so prospects never receive emails that get their basic facts wrong.",
    compatibility: {
      channels: ["Email", "LinkedIn"],
      methods: ["CSV export", "API"],
    },
    howItWorks: [
      { title: "ZoomInfo provides data, AI writes, Bookbag verifies", description: "ZoomInfo powers your prospect data. AI generates personalized outbound using it. Before those messages send, route them through Bookbag's AI Production Gate to verify data accuracy in the final email." },
      { title: "Wrong titles, outdated info, fabricated details get caught", description: "Each message gets a safe_to_deploy, needs_fix, or blocked verdict. Bookbag reviewers flag incorrect titles, outdated company information, wrong departments, and details the AI fabricated beyond ZoomInfo's data." },
      { title: "AI learns to use ZoomInfo data correctly", description: "Export correction pairs as SFT and DPO training data. Feed them back to improve how your AI uses ZoomInfo data — fewer wrong titles, more accurate company references." },
    ],
    benefits: [
      { title: "ZoomInfo contact data gets used correctly in emails", description: "ZoomInfo provides rich contact data, but AI can misuse it — wrong titles, wrong departments, wrong responsibilities. Bookbag catches these before your prospect sees an email that gets their job wrong." },
      { title: "Company data hallucinations don't reach prospects", description: "AI may hallucinate or misinterpret ZoomInfo company data — incorrect revenue ranges, wrong employee counts, fabricated technology references. Bookbag reviewers flag these before send." },
      { title: "Nothing kills outbound faster than wrong facts", description: "Getting a prospect's title, company size, or tech stack wrong undermines credibility instantly. Bookbag ensures AI-generated personalization built on ZoomInfo data is accurate before the prospect reads it." },
    ],
    faqs: [
      { question: "Does Bookbag connect directly to ZoomInfo?", answer: "No. The workflow is: ZoomInfo provides data, AI generates personalized outbound, and Bookbag reviews those messages for accuracy via CSV export or API. The gate sits between AI generation and send." },
      { question: "Can Bookbag catch outdated ZoomInfo data in AI messages?", answer: "Yes. Reviewers flag messages that reference details that appear outdated — old titles, former companies, stale tech stack references. The AI might use ZoomInfo data that hasn't been refreshed, and Bookbag catches it." },
      { question: "Does this work with ZoomInfo Engage?", answer: "Yes. Any AI-generated outbound triggered by ZoomInfo Engage workflows can be routed through Bookbag's AI Production Gate for verdict assignment before the message reaches the recipient." },
    ],
    relatedPersonas: ["b2b-saas", "revops"],
    relatedGlossary: ["ai-hallucination-detection", "outbound-deliverability-risk", "ai-brand-safety"],
    relatedComparison: "bookbag-vs-manual-review",
    relatedIntegrations: ["clearbit", "apollo"],
  },

  // ── Email Coaching ──────────────────────────────────────────────
  "lavender": {
    toolName: "Lavender",
    category: "Email Coaching",
    metaTitle: "Bookbag + Lavender Compatibility | Bookbag Intelligence",
    metaDescription: "Combine Lavender's email coaching with Bookbag's production gate. Score and gate AI outbound for maximum quality.",
    subtitle: "Bookbag works alongside Lavender's email coaching. Use both tools to ensure AI-generated outbound is polished and quality-gated before sending.",
    description: "Lavender scores your emails for reply rates and readability — it tells you whether an email will perform. But it doesn't tell you whether the email is factually accurate, compliant, or safe to send at scale. Bookbag and Lavender cover different quality dimensions: Lavender optimizes for engagement, Bookbag gates for accuracy and compliance. Use both.",
    compatibility: {
      channels: ["Email"],
      methods: ["CSV export", "Batch upload"],
    },
    howItWorks: [
      { title: "Lavender refines, then Bookbag gates", description: "Use Lavender to optimize AI-generated emails for reply rates and readability. Then route the Lavender-refined versions through Bookbag's AI Production Gate for human-authority review on accuracy, compliance, and brand safety." },
      { title: "Different quality layers catch different problems", description: "Lavender catches readability and engagement issues. Bookbag catches hallucinations, risky claims, compliance violations, and brand misalignment — the problems that scoring models structurally cannot detect." },
      { title: "Both tools improve from the same data", description: "Bookbag correction data shows which Lavender-optimized emails still had accuracy or compliance problems. Use this to calibrate both your Lavender templates and your Bookbag rubrics." },
    ],
    benefits: [
      { title: "Lavender optimizes engagement, Bookbag ensures safety", description: "Lavender tunes for reply rates. Bookbag verifies factual accuracy, compliance, and brand alignment. Together, they cover both performance and safety — an email that performs well and doesn't get you in trouble." },
      { title: "Scoring models miss what human reviewers catch", description: "Lavender's scoring catches readability and formatting issues. Bookbag's human reviewers catch hallucinated facts, risky competitive claims, and compliance violations that no scoring model can reliably detect." },
      { title: "An audit trail that a score can't provide", description: "Lavender gives you a number. Bookbag gives you a documented verdict with reviewer identity, rubric citations, and evidence — the kind of proof enterprise procurement and regulators actually accept." },
    ],
    faqs: [
      { question: "Does Bookbag replace Lavender?", answer: "No — they're complementary. Lavender optimizes email performance (reply rates, readability). Bookbag provides the AI Production Gate for accuracy, compliance, and brand safety. Use Lavender first, then route through Bookbag." },
      { question: "Should I run Lavender before or after Bookbag?", answer: "Lavender first. Optimize the email for engagement and readability, then route the refined version through Bookbag's gate. This way, Bookbag reviewers are evaluating the best version of the email for accuracy and compliance." },
      { question: "Can Bookbag reviewers see Lavender scores?", answer: "Bookbag doesn't ingest Lavender scores natively. But you can include scoring data as context for reviewers if you want them to consider engagement performance alongside accuracy and compliance review." },
    ],
    relatedPersonas: ["email-coaching-platforms", "sales-enablement"],
    relatedGlossary: ["ai-message-quality", "gold-standard-rewrites", "human-in-the-loop-ai"],
    relatedComparison: "rewrite-workflow-vs-prompt-tweaks",
    relatedIntegrations: ["copy-ai", "salesloft"],
  },

  "copy-ai": {
    toolName: "Copy.ai",
    category: "Email Coaching",
    metaTitle: "Bookbag + Copy.ai Compatibility | Bookbag Intelligence",
    metaDescription: "Gate AI-generated sales copy from Copy.ai through Bookbag. Add human-authority review to AI copywriting workflows.",
    subtitle: "Bookbag is compatible with AI-generated sales copy from Copy.ai. Route AI-written outbound content through human-authority review before deployment.",
    description: "Copy.ai generates sales email copy, outbound sequences, and templates fast. The risk: speed produces inconsistency. Copy.ai outputs vary in style, tone, and accuracy between runs — and AI copywriting tools have a habit of generating unsupported product claims or competitive comparisons. Bookbag gates every Copy.ai output before it enters your outbound workflow.",
    compatibility: {
      channels: ["Email"],
      methods: ["CSV export", "Batch upload"],
    },
    howItWorks: [
      { title: "Copy.ai writes, Bookbag reviews before deployment", description: "Generate sales email templates, outbound sequences, and personalized messaging in Copy.ai. Export the content and route it through Bookbag's AI Production Gate before importing into your sequencing or sending platform." },
      { title: "Brand voice and claims get verified", description: "Each piece of Copy.ai content receives a safe_to_deploy, needs_fix, or blocked verdict. Bookbag catches brand voice inconsistencies, unsupported product claims, and competitive comparisons that could backfire." },
      { title: "Approved Copy.ai content builds your template library", description: "Every reviewed and approved output becomes a vetted template you can reuse. needs_fix corrections show exactly how to improve future Copy.ai prompts — the library and the AI get better together." },
    ],
    benefits: [
      { title: "Copy.ai's speed with consistent brand voice", description: "Copy.ai generates content fast, but style varies between outputs. Bookbag ensures every piece of outbound copy matches your brand voice and messaging standards — no more tonal whiplash between emails." },
      { title: "Unsupported claims get caught before prospects see them", description: "AI copywriting tools generate product claims and competitive comparisons that may not be defensible. Bookbag reviewers flag these before they reach prospects and create legal or credibility risk." },
      { title: "Every review builds a vetted template library", description: "Approved Copy.ai outputs build a library of production-tested sales messaging. Reuse these templates with confidence — they passed human-authority review against your specific rubrics." },
    ],
    faqs: [
      { question: "Does Bookbag integrate with Copy.ai?", answer: "There's no native integration, but export and upload works well. Generate content in Copy.ai, export it, and route through Bookbag via CSV export or batch upload. Most teams are live in under an hour." },
      { question: "Can Bookbag review Copy.ai workflow outputs?", answer: "Yes. Any text-based content from Copy.ai — email copy, sequences, subject lines, outbound templates, and ad copy — can be routed through Bookbag's AI Production Gate for verdict assignment." },
      { question: "Is this overkill for simple email templates?", answer: "No. AI introduces factual errors, compliance issues, and off-brand language in even simple outputs. The cost of one bad template multiplied across your send volume is the real risk. Bookbag ensures everything that ships meets your standards." },
    ],
    relatedPersonas: ["sales-enablement", "b2b-saas"],
    relatedGlossary: ["ai-brand-safety", "gold-standard-rewrites", "sft-export"],
    relatedComparison: "bookbag-vs-prompt-engineering",
    relatedIntegrations: ["lavender", "regie-ai"],
  },
}

export function getIntegration(slug) {
  return integrations[slug] || null
}

export function getAllIntegrationSlugs() {
  return Object.keys(integrations)
}
