export const integrations = {
  // ── AI SDR Platforms ────────────────────────────────────────────
  "11x": {
    toolName: "11x",
    category: "AI SDR Platform",
    metaTitle: "Bookbag + 11x Compatibility | Bookbag Intelligence",
    metaDescription: "Route AI messages generated by 11x's Jessica agent through Bookbag's production gate. Catch hallucinations before they ship.",
    subtitle: "Bookbag is compatible with outbound messages generated by 11x's AI SDR agent, Jessica. Gate every AI-written email before it reaches your prospects.",
    description: "11x builds autonomous AI workers for go-to-market teams. Their AI SDR agent, Jessica, automates prospect research and outbound email generation at scale. 11x is designed to replace manual SDR workflows with fully autonomous outreach.",
    howItWorks: [
      { title: "Export messages from 11x", description: "Pull AI-generated outbound drafts from your 11x workspace. Jessica produces high volumes of personalized emails that can be routed through Bookbag before sending." },
      { title: "Gate through Bookbag", description: "Route 11x-generated messages through Bookbag's safe/fix/block lanes. Each email receives a verdict based on your configured rubrics for tone, accuracy, and compliance." },
      { title: "Ship approved messages", description: "Safe messages are approved automatically. Fixed messages return with gold-standard rewrites. Blocked messages get SME review before any decision is made." },
    ],
    benefits: [
      { title: "Catch Jessica's blind spots", description: "Even the best AI SDR agents hallucinate or misjudge tone. Bookbag catches these issues before they damage your sender reputation or brand." },
      { title: "Build training data from corrections", description: "Every correction Bookbag makes to a Jessica-generated email becomes an exportable training pair you can use to improve your AI outbound over time." },
      { title: "Enterprise-grade audit trail", description: "Prove to procurement and compliance teams that every AI-generated message was reviewed by human authority before delivery." },
    ],
    faqs: [
      { question: "Does Bookbag have a direct integration with 11x?", answer: "Bookbag is compatible with 11x outputs. You can route Jessica-generated messages through Bookbag via batch upload or API. A direct platform integration is planned." },
      { question: "How many messages can Bookbag gate from 11x?", answer: "Bookbag scales to handle the volume 11x produces. Plans range from hundreds to millions of messages per month depending on your tier." },
      { question: "Will gating slow down 11x's autonomous workflow?", answer: "Safe messages auto-approve with no meaningful delay. Only flagged items enter the human review queue, so the majority of Jessica's output ships quickly." },
    ],
    relatedPersonas: ["ai-sdr-vendors", "revops"],
    relatedGlossary: ["ai-production-gate", "ai-hallucination-detection", "safe-to-deploy"],
    relatedComparison: "bookbag-vs-prompt-engineering",
    relatedIntegrations: ["artisan", "aisdr"],
  },

  "artisan": {
    toolName: "Artisan",
    category: "AI SDR Platform",
    metaTitle: "Bookbag + Artisan Compatibility | Bookbag Intelligence",
    metaDescription: "Gate AI outbound from Artisan's Ava agent through Bookbag. Add human-authority QA to every AI-generated sales email.",
    subtitle: "Bookbag is compatible with outbound messages generated by Artisan's AI sales agent, Ava. Add a quality gate between AI generation and prospect delivery.",
    description: "Artisan builds AI employees for outbound sales. Their flagship agent, Ava, handles lead research, email personalization, and outbound sequencing autonomously. Artisan aims to automate the full top-of-funnel sales workflow.",
    howItWorks: [
      { title: "Collect Ava's drafts", description: "Export or intercept AI-generated emails from Artisan's platform before they are sent. Ava produces personalized outbound at scale that benefits from quality review." },
      { title: "Run through Bookbag's gate", description: "Each message is evaluated against your rubrics. Bookbag routes outputs into safe (auto-approved), fix (QA corrects), or block (SME reviews) lanes." },
      { title: "Return approved content", description: "Approved and corrected messages are ready to send through your sequencing tool. Every verdict is logged with reviewer identity and rubric citations." },
    ],
    benefits: [
      { title: "Protect sender reputation", description: "Ava generates high-volume outbound. One bad batch can torch your domain. Bookbag catches risky messages before they hit inboxes." },
      { title: "Compliance documentation", description: "Every AI-generated email has a documented review verdict. This satisfies enterprise procurement requirements for AI governance and oversight." },
      { title: "Continuous AI improvement", description: "Corrections to Ava's output become structured training data. Export SFT or DPO pairs to improve personalization quality over time." },
    ],
    faqs: [
      { question: "Is there a native Bookbag-Artisan integration?", answer: "Bookbag is compatible with Artisan's outputs. You can route Ava-generated messages through Bookbag via upload or API. A native integration is on the roadmap." },
      { question: "Does Bookbag replace Artisan's built-in quality checks?", answer: "No. Bookbag adds an independent human-authority layer on top of whatever internal checks Artisan provides. Think of it as an additional production gate, not a replacement." },
      { question: "What if Ava's email references incorrect company data?", answer: "Bookbag reviewers flag hallucinated facts, wrong company details, and inaccurate claims. These corrections prevent embarrassing outreach and generate training data to reduce future errors." },
    ],
    relatedPersonas: ["ai-sdr-vendors", "head-of-cs"],
    relatedGlossary: ["ai-hallucination-detection", "gold-standard-rewrites", "ai-message-quality"],
    relatedComparison: "bookbag-vs-internal-qa",
    relatedIntegrations: ["11x", "aisdr"],
  },

  "aisdr": {
    toolName: "AiSDR",
    category: "AI SDR Platform",
    metaTitle: "Bookbag + AiSDR Compatibility | Bookbag Intelligence",
    metaDescription: "Route AiSDR-generated outbound through Bookbag's production gate. Add human review to AI sales emails before they send.",
    subtitle: "Bookbag is compatible with messages generated by AiSDR. Gate AI-written sales emails through human-authority review before they reach prospects.",
    description: "AiSDR is an AI-powered sales development platform that automates personalized outbound email creation. It uses AI to research prospects and generate tailored messages designed to book meetings.",
    howItWorks: [
      { title: "Route AiSDR output to Bookbag", description: "Export AI-generated email drafts from AiSDR. These messages can be sent to Bookbag via batch upload or API before entering your sending queue." },
      { title: "Apply rubric-based review", description: "Bookbag evaluates each message against your configured rubrics covering tone, factual accuracy, compliance language, and personalization quality." },
      { title: "Approve and send", description: "Clean messages auto-approve. Corrected messages return with gold-standard rewrites. Blocked messages receive SME authority review with documented rationale." },
    ],
    benefits: [
      { title: "Quality at AI speed", description: "AiSDR generates outbound fast. Bookbag ensures that speed does not come at the cost of accuracy or brand safety." },
      { title: "Training data from every correction", description: "Each fix to an AiSDR message is a structured before/after pair. Export these to improve your AI outbound quality over time." },
      { title: "Audit-ready oversight", description: "Regulated industries and enterprise buyers need proof of human review. Bookbag provides timestamped, attributed verdicts for every AI message." },
    ],
    faqs: [
      { question: "Can Bookbag handle AiSDR's output volume?", answer: "Yes. Bookbag is built for high-volume AI outbound. Safe messages auto-approve instantly, and only flagged items require human review time." },
      { question: "Does this work with AiSDR's LinkedIn messaging?", answer: "Bookbag can gate any text-based AI output including LinkedIn messages, emails, and SMS. Route any AiSDR-generated content through the production gate." },
      { question: "How do I connect AiSDR to Bookbag?", answer: "You can route AiSDR outputs through Bookbag via batch upload or API. There is no native plugin yet, but the workflow is straightforward with CSV or API-based message transfer." },
    ],
    relatedPersonas: ["ai-sdr-vendors", "vp-product"],
    relatedGlossary: ["ai-production-gate", "sft-export", "needs-fix"],
    relatedComparison: "bookbag-vs-prompt-engineering",
    relatedIntegrations: ["11x", "artisan"],
  },

  "regie-ai": {
    toolName: "Regie.ai",
    category: "AI SDR Platform",
    metaTitle: "Bookbag + Regie.ai Compatibility | Bookbag Intelligence",
    metaDescription: "Add a production gate to Regie.ai-generated sales content. Route AI sequences through Bookbag for human-authority review.",
    subtitle: "Bookbag is compatible with AI-generated sales content from Regie.ai. Add human-authority quality gating to your AI engagement workflows.",
    description: "Regie.ai is an AI sales engagement platform that generates personalized outbound sequences, manages prospecting workflows, and helps sales teams scale their outreach with AI-powered content creation.",
    howItWorks: [
      { title: "Export Regie.ai sequences", description: "Pull AI-generated sequence steps from Regie.ai. These emails and messages can be routed through Bookbag before being activated in your engagement platform." },
      { title: "Evaluate with Bookbag rubrics", description: "Each sequence step is reviewed against your quality rubrics. Bookbag catches hallucinations, tone mismatches, and compliance risks across entire multi-step sequences." },
      { title: "Deploy reviewed sequences", description: "Approved sequence steps return to your workflow. Corrections include gold-standard rewrites with documented rationale for every change." },
    ],
    benefits: [
      { title: "Sequence-level quality control", description: "Regie.ai builds multi-step sequences. Bookbag can evaluate each step for consistency, escalation in tone, and cumulative compliance risk across the sequence." },
      { title: "Protect domain deliverability", description: "AI-generated sequences sent at scale can trigger spam signals. Bookbag catches risky language and aggressive patterns before they damage your sending domains." },
      { title: "Evidence-based corrections", description: "Every correction includes rubric citations and reviewer rationale. Use these to refine your Regie.ai prompts and templates over time." },
    ],
    faqs: [
      { question: "Does Bookbag integrate directly with Regie.ai?", answer: "Bookbag is compatible with Regie.ai outputs. You can route generated content through Bookbag via batch upload or API. A direct integration is planned." },
      { question: "Can Bookbag review an entire sequence at once?", answer: "Yes. You can submit multi-step sequences for review. Bookbag evaluates each step individually and can flag sequence-level issues like tone escalation or repetitive messaging." },
      { question: "How does this improve Regie.ai's output over time?", answer: "Corrections generate structured training data. Export these before/after pairs to refine your AI content generation, creating a feedback loop that improves quality continuously." },
    ],
    relatedPersonas: ["sequencing-platforms", "sales-enablement"],
    relatedGlossary: ["ai-message-quality", "gold-standard-rewrites", "rubric-versioning"],
    relatedComparison: "rewrite-workflow-vs-prompt-tweaks",
    relatedIntegrations: ["salesforge", "jason-ai"],
  },

  "salesforge": {
    toolName: "Salesforge",
    category: "AI SDR Platform",
    metaTitle: "Bookbag + Salesforge Compatibility | Bookbag Intelligence",
    metaDescription: "Gate Salesforge AI-personalized emails through Bookbag before sending. Ensure every AI email meets quality and compliance standards.",
    subtitle: "Bookbag is compatible with AI-personalized emails from Salesforge. Route AI outputs through human-authority review before they reach prospects.",
    description: "Salesforge is an AI email personalization and sending platform that generates unique, personalized cold emails at scale. It combines AI writing with deliverability infrastructure to help sales teams run outbound campaigns.",
    howItWorks: [
      { title: "Intercept Salesforge drafts", description: "Route AI-personalized email drafts from Salesforge through Bookbag before they enter the sending queue. This adds a quality checkpoint between generation and delivery." },
      { title: "Apply production gate review", description: "Bookbag evaluates each personalized email for factual accuracy, tone, compliance, and brand alignment using your configured rubric criteria." },
      { title: "Release approved emails", description: "Approved emails proceed to Salesforge's sending infrastructure. Fixed emails return with corrections. Blocked emails receive SME review." },
    ],
    benefits: [
      { title: "Personalization accuracy", description: "AI personalization can reference wrong details about prospects or companies. Bookbag catches these errors before they become embarrassing outreach." },
      { title: "Scale with confidence", description: "Salesforge is built for volume. Bookbag ensures that high-volume AI personalization does not mean high-volume quality risk." },
      { title: "Deliverability protection", description: "Spammy AI-generated content damages sender reputation. Bookbag flags aggressive language, excessive claims, and patterns that trigger spam filters." },
    ],
    faqs: [
      { question: "How do I route Salesforge emails through Bookbag?", answer: "Export AI-generated drafts from Salesforge and submit them to Bookbag via batch upload or API. Approved messages can then be sent through Salesforge's infrastructure." },
      { question: "Does this add latency to my Salesforge campaigns?", answer: "Safe messages auto-approve with minimal delay. Only flagged messages require human review time. Most teams see 70-85% auto-approval rates after calibration." },
      { question: "Can Bookbag handle Salesforge's multi-language output?", answer: "Bookbag supports review of messages in multiple languages. Configure rubrics per language to ensure quality standards are met across your international campaigns." },
    ],
    relatedPersonas: ["cold-email-infrastructure", "revops"],
    relatedGlossary: ["outbound-deliverability-risk", "ai-brand-safety", "safe-to-deploy"],
    relatedComparison: "quality-gate-vs-deliverability-tooling",
    relatedIntegrations: ["regie-ai", "instantly"],
  },

  "jason-ai": {
    toolName: "Jason AI",
    category: "AI SDR Platform",
    metaTitle: "Bookbag + Jason AI Compatibility | Bookbag Intelligence",
    metaDescription: "Route Jason AI outbound messages through Bookbag's production gate. Add human-authority review to Reply.io's AI SDR.",
    subtitle: "Bookbag is compatible with outbound messages from Jason AI, Reply.io's AI SDR assistant. Gate AI-generated emails before they reach prospects.",
    description: "Jason AI is Reply.io's AI-powered SDR assistant that automates outbound prospecting, generates personalized emails, and handles initial prospect responses. It operates within the Reply.io sales engagement platform.",
    howItWorks: [
      { title: "Capture Jason AI outputs", description: "Export or intercept AI-generated messages from Jason AI within your Reply.io workspace. These drafts can be routed to Bookbag before sending." },
      { title: "Review against your rubrics", description: "Bookbag evaluates each Jason AI message for accuracy, tone, compliance, and personalization quality. Messages are routed to safe, fix, or block lanes." },
      { title: "Send reviewed messages via Reply.io", description: "Approved messages return to your Reply.io sending workflow. Every verdict is documented with reviewer identity, rubric citations, and timestamps." },
    ],
    benefits: [
      { title: "Oversight for autonomous responses", description: "Jason AI can respond to prospect replies autonomously. Bookbag provides a checkpoint to ensure AI follow-up messages meet your standards." },
      { title: "Reduce risk in Reply.io campaigns", description: "High-volume Reply.io campaigns powered by Jason AI carry deliverability risk. Bookbag catches the messages that could damage your sender domains." },
      { title: "Structured improvement data", description: "Corrections to Jason AI outputs become training pairs. Use these to improve Reply.io's AI personalization quality in future campaigns." },
    ],
    faqs: [
      { question: "Does Bookbag connect directly to Reply.io?", answer: "Bookbag is compatible with Jason AI and Reply.io outputs. You can route messages through Bookbag via batch upload or API. A direct Reply.io integration is planned." },
      { question: "Can Bookbag review Jason AI's auto-responses?", answer: "Yes. Any text-based AI output can be gated through Bookbag, including automated responses Jason AI generates to prospect replies." },
      { question: "Will this slow down my Reply.io sequences?", answer: "Safe messages auto-approve instantly. Only flagged items enter the review queue. Most outbound passes through without delay after rubric calibration." },
    ],
    relatedPersonas: ["ai-sdr-vendors", "sales-enablement"],
    relatedGlossary: ["message-gating", "needs-fix", "annotator-calibration"],
    relatedComparison: "bookbag-vs-prompt-engineering",
    relatedIntegrations: ["regie-ai", "apollo"],
  },

  // ── Sequencing Platforms ────────────────────────────────────────
  "apollo": {
    toolName: "Apollo",
    category: "Sequencing Platform",
    metaTitle: "Bookbag + Apollo Compatibility | Bookbag Intelligence",
    metaDescription: "Gate AI-generated Apollo sequences through Bookbag. Add human-authority QA before AI emails reach your prospects.",
    subtitle: "Bookbag is compatible with AI-generated sequences and emails from Apollo. Add a production gate to your Apollo outbound workflow.",
    description: "Apollo is a sales intelligence and engagement platform that combines a B2B contact database with email sequencing, dialer, and AI-powered message generation. It is widely used by SDR teams for prospecting and outbound campaigns.",
    howItWorks: [
      { title: "Export Apollo AI sequences", description: "Pull AI-generated email sequences and one-off messages from Apollo. These drafts can be routed through Bookbag before activating in your Apollo sequences." },
      { title: "Gate with Bookbag verdicts", description: "Each message receives a safe, fix, or block verdict. Bookbag evaluates factual claims, personalization accuracy, tone, and compliance against your rubric." },
      { title: "Activate approved sequences", description: "Approved messages go back into Apollo for sending. Corrections and verdicts are logged for audit compliance and training data export." },
    ],
    benefits: [
      { title: "Data accuracy layer", description: "Apollo provides contact and company data that feeds AI personalization. Bookbag catches cases where AI misuses or hallucinates on top of that data." },
      { title: "Scale Apollo AI safely", description: "Apollo's AI features generate messages quickly. Bookbag ensures that scaling AI-generated outbound does not mean scaling quality risk." },
      { title: "Exportable training data", description: "Every correction to an Apollo AI message becomes a structured training pair. Use these to improve future AI sequence quality." },
    ],
    faqs: [
      { question: "Does Bookbag have a direct Apollo integration?", answer: "Bookbag is compatible with Apollo's AI-generated outputs. You can route messages through Bookbag via batch upload or API. A direct integration is planned." },
      { question: "Can I gate Apollo sequences before they go live?", answer: "Yes. Export draft sequences from Apollo, run them through Bookbag's production gate, and activate only the approved versions in your Apollo workspace." },
      { question: "Does this work with Apollo's AI email writer?", answer: "Yes. Any AI-generated text from Apollo — including AI-written emails, subject lines, and sequence steps — can be routed through Bookbag for review." },
    ],
    relatedPersonas: ["sequencing-platforms", "revops"],
    relatedGlossary: ["ai-production-gate", "safe-to-deploy", "qa-review-workflow"],
    relatedComparison: "bookbag-vs-internal-qa",
    relatedIntegrations: ["salesloft", "outreach"],
  },

  "salesloft": {
    toolName: "Salesloft",
    category: "Sequencing Platform",
    metaTitle: "Bookbag + Salesloft Compatibility | Bookbag Intelligence",
    metaDescription: "Add a production gate to AI-generated Salesloft cadences. Route AI emails through Bookbag for human-authority review.",
    subtitle: "Bookbag is compatible with AI-generated cadence content from Salesloft. Gate AI emails and sequence steps through human-authority review.",
    description: "Salesloft is a leading sales engagement platform used by revenue teams to build multi-channel cadences, automate outreach, and manage buyer engagement. It increasingly incorporates AI features for message generation and optimization.",
    howItWorks: [
      { title: "Collect AI-generated cadence steps", description: "Export AI-generated email steps from Salesloft cadences. These can be routed to Bookbag before reps begin executing the cadence." },
      { title: "Review through Bookbag's gate", description: "Each cadence step is evaluated for quality, compliance, and brand alignment. Multi-step cadences can be reviewed for consistency and tone escalation across the sequence." },
      { title: "Deploy approved cadences", description: "Approved steps return to Salesloft. Reps execute cadences knowing every AI-generated touchpoint has been reviewed and approved." },
    ],
    benefits: [
      { title: "Cadence-level quality assurance", description: "AI-generated cadences need consistency across steps. Bookbag reviews each step and flags tone shifts, contradictions, or cumulative compliance risk." },
      { title: "Rep confidence", description: "Sales reps execute AI-generated cadences more confidently when they know every message has been reviewed by qualified annotators." },
      { title: "Governance for AI adoption", description: "As Salesloft adds more AI features, Bookbag provides the governance layer that enterprise buyers require before approving AI-assisted outreach." },
    ],
    faqs: [
      { question: "Does Bookbag integrate directly with Salesloft?", answer: "Bookbag is compatible with Salesloft outputs. You can route AI-generated cadence content through Bookbag via batch upload or API. A direct integration is planned." },
      { question: "Can Bookbag review Salesloft AI-generated subject lines?", answer: "Yes. Bookbag can gate any text-based AI output, including subject lines, email bodies, and call scripts generated within Salesloft." },
      { question: "How do I get started with Salesloft and Bookbag?", answer: "Export a sample cadence from Salesloft, upload it to Bookbag for review, and see verdicts within your SLA window. Most teams start with a pilot batch before scaling." },
    ],
    relatedPersonas: ["sequencing-platforms", "sales-enablement"],
    relatedGlossary: ["message-gating", "rubric-versioning", "gold-standard-rewrites"],
    relatedComparison: "bookbag-vs-manual-review",
    relatedIntegrations: ["outreach", "apollo"],
  },

  "outreach": {
    toolName: "Outreach",
    category: "Sequencing Platform",
    metaTitle: "Bookbag + Outreach Compatibility | Bookbag Intelligence",
    metaDescription: "Route AI-generated Outreach sequences through Bookbag's production gate. Add human-authority review to AI sales emails.",
    subtitle: "Bookbag is compatible with AI-generated content from Outreach. Add a quality gate to AI-powered sequences before they reach prospects.",
    description: "Outreach is a sales execution platform used by revenue teams to manage sequences, automate multi-channel engagement, and drive pipeline. Its AI capabilities help generate email content and optimize send timing.",
    howItWorks: [
      { title: "Pull AI content from Outreach", description: "Export AI-generated sequence emails and templates from Outreach. Route these drafts to Bookbag for review before activating sequences." },
      { title: "Evaluate against your rubrics", description: "Bookbag reviews each message for accuracy, tone, compliance, and brand standards. Verdicts route to safe (auto-approve), fix (QA review), or block (SME authority)." },
      { title: "Activate reviewed sequences", description: "Approved content returns to Outreach for execution. Every verdict is logged for audit compliance, and corrections generate training data." },
    ],
    benefits: [
      { title: "Enterprise-ready AI outbound", description: "Outreach is widely used in enterprise sales orgs. Bookbag adds the governance layer that procurement teams require for AI-assisted outreach." },
      { title: "Protect high-value accounts", description: "Enterprise sequences targeting strategic accounts cannot afford AI errors. Bookbag ensures every touchpoint is reviewed before it reaches key decision-makers." },
      { title: "Continuous sequence improvement", description: "Corrections to Outreach AI content build a library of approved messaging. Use this to improve future sequence generation and train reps on what good looks like." },
    ],
    faqs: [
      { question: "Is there a native Bookbag-Outreach integration?", answer: "Bookbag is compatible with Outreach outputs. You can route AI-generated content through Bookbag via batch upload or API. A native integration is planned." },
      { question: "Can Bookbag handle Outreach's volume?", answer: "Yes. Bookbag's production gate is designed for high-volume outbound. Safe messages auto-approve, and only flagged items require human review." },
      { question: "Does this work with Outreach's AI email features?", answer: "Yes. Any AI-generated text from Outreach — including Smart Email Assist and AI-generated templates — can be routed through Bookbag for quality review." },
    ],
    relatedPersonas: ["sequencing-platforms", "revops"],
    relatedGlossary: ["ai-production-gate", "ai-audit-trail", "safe-to-deploy"],
    relatedComparison: "bookbag-vs-internal-qa",
    relatedIntegrations: ["salesloft", "apollo"],
  },

  "hubspot-sales-hub": {
    toolName: "HubSpot Sales Hub",
    category: "Sequencing Platform",
    metaTitle: "Bookbag + HubSpot Sales Hub | Bookbag Intelligence",
    metaDescription: "Gate AI-generated HubSpot Sales Hub emails through Bookbag. Add human review to AI sequences before they reach contacts.",
    subtitle: "Bookbag is compatible with AI-generated content from HubSpot Sales Hub. Route AI emails and sequence content through human-authority review.",
    description: "HubSpot Sales Hub is a CRM-integrated sales platform with email sequencing, pipeline management, and AI-powered content generation tools. It is widely adopted across SMB and mid-market sales teams.",
    howItWorks: [
      { title: "Export HubSpot AI content", description: "Pull AI-generated email drafts, sequence steps, and templates from HubSpot Sales Hub. Route these through Bookbag before activating in your sequences." },
      { title: "Review with Bookbag rubrics", description: "Each message is evaluated for quality, compliance, and brand alignment. HubSpot's AI features generate content that benefits from independent quality review." },
      { title: "Return to HubSpot workflow", description: "Approved content goes back into your HubSpot sequences. Verdicts, corrections, and audit trails are documented for every message." },
    ],
    benefits: [
      { title: "CRM-aware quality gating", description: "HubSpot centralizes contact data and outreach. Bookbag ensures that AI-generated messages using that data are accurate and compliant before delivery." },
      { title: "Governance for growing teams", description: "As teams scale AI usage in HubSpot, Bookbag provides the oversight layer that prevents quality from degrading with volume." },
      { title: "Training data for AI improvement", description: "Corrections to HubSpot AI outputs become structured training data. Export these to improve your AI content generation over time." },
    ],
    faqs: [
      { question: "Does Bookbag integrate with HubSpot directly?", answer: "Bookbag is compatible with HubSpot Sales Hub outputs. You can route AI-generated content through Bookbag via batch upload or API. A direct HubSpot integration is planned." },
      { question: "Can I gate HubSpot's AI email writer outputs?", answer: "Yes. Any AI-generated content from HubSpot — including the AI email writer, sequence suggestions, and template generation — can be routed through Bookbag." },
      { question: "Is this relevant for HubSpot Marketing Hub too?", answer: "Bookbag focuses on outbound sales messaging. If your marketing team generates AI-powered outbound emails in HubSpot, those can also be gated through Bookbag." },
    ],
    relatedPersonas: ["b2b-saas", "sales-enablement"],
    relatedGlossary: ["ai-message-quality", "qa-review-workflow", "audit-ready-review"],
    relatedComparison: "bookbag-vs-manual-review",
    relatedIntegrations: ["salesloft", "outreach"],
  },

  // ── Cold Email Infrastructure ───────────────────────────────────
  "smartlead": {
    toolName: "Smartlead",
    category: "Cold Email Infrastructure",
    metaTitle: "Bookbag + Smartlead Compatibility | Bookbag Intelligence",
    metaDescription: "Route AI-generated cold emails through Bookbag before sending via Smartlead. Protect deliverability with human-authority QA.",
    subtitle: "Bookbag is compatible with cold email content sent through Smartlead. Gate AI-generated messages before they enter Smartlead's sending infrastructure.",
    description: "Smartlead is a cold email infrastructure platform designed for high-volume outbound. It manages mailbox rotation, warm-up, and deliverability optimization for cold email campaigns at scale.",
    howItWorks: [
      { title: "Review content before import", description: "Before loading AI-generated email content into Smartlead, route it through Bookbag's production gate. This ensures only reviewed messages enter your sending infrastructure." },
      { title: "Gate against quality rubrics", description: "Bookbag evaluates each email for spam triggers, compliance language, factual accuracy, and tone. Messages receive safe, fix, or block verdicts." },
      { title: "Load approved content into Smartlead", description: "Only approved and corrected emails are imported into Smartlead for sending. This protects your warmed-up domains and mailbox reputation." },
    ],
    benefits: [
      { title: "Deliverability protection", description: "Smartlead invests in domain warm-up and mailbox health. One batch of spammy AI content can undo weeks of warm-up. Bookbag prevents this." },
      { title: "Pre-send quality assurance", description: "High-volume cold email amplifies every quality issue. Bookbag catches problems before they scale across thousands of sends." },
      { title: "Spam trigger detection", description: "Bookbag reviewers flag language patterns, excessive claims, and formatting issues that commonly trigger spam filters in cold email." },
    ],
    faqs: [
      { question: "Does Bookbag integrate with Smartlead's API?", answer: "Bookbag is compatible with content destined for Smartlead. Review emails through Bookbag first, then import approved content into Smartlead. A direct integration is planned." },
      { question: "How does this protect my Smartlead warm-up?", answer: "Bookbag catches spammy language, compliance violations, and aggressive tone before emails enter Smartlead's sending queue. This prevents AI-generated content from damaging your warmed-up infrastructure." },
      { question: "Can Bookbag review Smartlead campaign variants?", answer: "Yes. Submit all campaign variants and A/B test versions through Bookbag. Each variant receives an independent verdict so you know which versions are safe to send." },
    ],
    relatedPersonas: ["cold-email-infrastructure", "deliverability-agencies"],
    relatedGlossary: ["outbound-deliverability-risk", "message-gating", "safe-to-deploy"],
    relatedComparison: "quality-gate-vs-deliverability-tooling",
    relatedIntegrations: ["instantly", "lemlist"],
  },

  "instantly": {
    toolName: "Instantly",
    category: "Cold Email Infrastructure",
    metaTitle: "Bookbag + Instantly Compatibility | Bookbag Intelligence",
    metaDescription: "Gate AI cold emails before sending through Instantly. Protect your domains with Bookbag's human-authority production gate.",
    subtitle: "Bookbag is compatible with cold email content sent through Instantly. Review AI-generated messages before they enter Instantly's sending infrastructure.",
    description: "Instantly is a cold email sending platform built for scale. It provides mailbox warm-up, domain rotation, campaign management, and deliverability features for high-volume cold outbound teams.",
    howItWorks: [
      { title: "Gate content before Instantly", description: "Route AI-generated email copy through Bookbag before importing it into Instantly campaigns. This adds a quality layer between content creation and sending." },
      { title: "Evaluate for deliverability risks", description: "Bookbag reviews each email for spam-trigger language, compliance issues, factual claims, and tone. Verdicts route messages to safe, fix, or block lanes." },
      { title: "Import approved content", description: "Only reviewed and approved emails enter your Instantly campaigns. This protects your domain reputation and warm-up investment." },
    ],
    benefits: [
      { title: "Protect domain investment", description: "Instantly users invest heavily in domain and mailbox setup. Bookbag prevents AI-generated content from burning those assets with spammy or risky messages." },
      { title: "Scale safely", description: "Instantly enables high-volume sending. Bookbag ensures that scaling volume does not mean scaling the risk of deliverability-damaging content." },
      { title: "Compliance at scale", description: "Cold email at volume requires careful compliance management. Bookbag catches CAN-SPAM and other regulatory issues before they are sent to thousands of recipients." },
    ],
    faqs: [
      { question: "How do I use Bookbag with Instantly?", answer: "Generate your AI email content, route it through Bookbag for review, and import approved messages into Instantly. This pre-send workflow adds quality control without changing your Instantly setup." },
      { question: "Does Bookbag check for spam triggers?", answer: "Yes. Bookbag reviewers flag language patterns, formatting issues, and content that commonly triggers spam filters. This is especially important for high-volume cold email." },
      { question: "Can I review Instantly lead list messages?", answer: "Yes. Submit AI-personalized messages for your lead lists through Bookbag before importing them into Instantly campaigns. Each message receives an individual verdict." },
    ],
    relatedPersonas: ["cold-email-infrastructure", "revops"],
    relatedGlossary: ["outbound-deliverability-risk", "can-spam-ai-messaging", "blocked-verdict"],
    relatedComparison: "quality-gate-vs-deliverability-tooling",
    relatedIntegrations: ["smartlead", "lemlist"],
  },

  "lemlist": {
    toolName: "Lemlist",
    category: "Cold Email Infrastructure",
    metaTitle: "Bookbag + Lemlist Compatibility | Bookbag Intelligence",
    metaDescription: "Route AI-personalized Lemlist campaigns through Bookbag before sending. Add human-authority QA to outbound at scale.",
    subtitle: "Bookbag is compatible with AI-generated outreach content from Lemlist. Gate personalized cold emails through human-authority review.",
    description: "Lemlist is a cold outreach and personalization platform that helps sales teams create personalized email campaigns with dynamic images, custom landing pages, and AI-powered content. It combines creative personalization with cold email sending.",
    howItWorks: [
      { title: "Export Lemlist AI content", description: "Pull AI-generated email copy and personalization variables from Lemlist. Route these through Bookbag before launching your campaign." },
      { title: "Review personalization quality", description: "Bookbag evaluates each personalized email for accuracy, tone, and compliance. AI personalization that references wrong details or makes unsupported claims gets flagged." },
      { title: "Launch approved campaigns", description: "Import reviewed and approved content back into Lemlist. Only messages that passed the production gate enter your sending queue." },
    ],
    benefits: [
      { title: "Personalization accuracy", description: "Lemlist's AI personalization features generate unique content per prospect. Bookbag catches cases where personalization goes wrong — wrong company details, incorrect titles, or fabricated facts." },
      { title: "Creative quality control", description: "Lemlist enables creative outreach formats. Bookbag ensures that AI-generated creative content meets brand and quality standards before it reaches prospects." },
      { title: "Reusable correction library", description: "Corrections to Lemlist AI content build a library of approved personalization patterns. Use these as templates and training data for future campaigns." },
    ],
    faqs: [
      { question: "Does Bookbag integrate directly with Lemlist?", answer: "Bookbag is compatible with Lemlist outputs. Route AI-generated content through Bookbag via batch upload or API before launching Lemlist campaigns. A direct integration is planned." },
      { question: "Can Bookbag check Lemlist custom variables?", answer: "Yes. Submit fully rendered emails with all variables populated. Bookbag reviews the final message as the prospect would see it, catching issues in personalization data." },
      { question: "Is this useful for Lemlist's LinkedIn outreach?", answer: "Yes. Bookbag can gate any text-based outbound, including LinkedIn messages generated through Lemlist's multi-channel campaigns." },
    ],
    relatedPersonas: ["cold-email-infrastructure", "b2b-saas"],
    relatedGlossary: ["ai-brand-safety", "gold-standard-rewrites", "ai-message-quality"],
    relatedComparison: "rewrite-workflow-vs-prompt-tweaks",
    relatedIntegrations: ["smartlead", "woodpecker"],
  },

  "woodpecker": {
    toolName: "Woodpecker",
    category: "Cold Email Infrastructure",
    metaTitle: "Bookbag + Woodpecker Compatibility | Bookbag Intelligence",
    metaDescription: "Gate AI-generated Woodpecker campaigns through Bookbag. Add human review to cold email before sending at scale.",
    subtitle: "Bookbag is compatible with cold email content sent through Woodpecker. Review AI-generated campaigns before they reach prospects.",
    description: "Woodpecker is a cold email automation platform designed for B2B outbound. It provides email sequencing, follow-up automation, deliverability monitoring, and A/B testing for cold outreach campaigns.",
    howItWorks: [
      { title: "Review before loading campaigns", description: "Route AI-generated email content through Bookbag before importing it into Woodpecker campaigns. This ensures only quality-checked content enters your sending workflow." },
      { title: "Evaluate campaign content", description: "Bookbag reviews each email and follow-up for compliance, factual accuracy, and tone. A/B variants each receive independent verdicts." },
      { title: "Import approved emails", description: "Load approved content into Woodpecker. Corrections and verdicts are documented, creating an audit trail for your cold email campaigns." },
    ],
    benefits: [
      { title: "Follow-up quality", description: "Woodpecker automates follow-ups. Bookbag ensures that AI-generated follow-up sequences maintain appropriate tone and do not escalate into aggressive or non-compliant messaging." },
      { title: "A/B test safety", description: "Review all A/B variants before testing. Bookbag catches risky variants that could damage deliverability during your test campaigns." },
      { title: "Compliance documentation", description: "Cold email campaigns need compliance oversight. Bookbag provides documented review verdicts for every email in your Woodpecker campaigns." },
    ],
    faqs: [
      { question: "How do I connect Bookbag with Woodpecker?", answer: "Route AI-generated email content through Bookbag via batch upload or API, then import approved content into Woodpecker. There is no direct plugin yet, but the workflow is straightforward." },
      { question: "Can Bookbag review Woodpecker follow-up sequences?", answer: "Yes. Submit entire follow-up sequences for review. Bookbag evaluates each step for quality and flags issues like tone escalation or repetitive messaging across the sequence." },
      { question: "Does this work with Woodpecker's agency features?", answer: "Yes. Agencies managing multiple client campaigns in Woodpecker can route all AI-generated content through Bookbag. Each client's rubrics can be configured independently." },
    ],
    relatedPersonas: ["cold-email-infrastructure", "deliverability-agencies"],
    relatedGlossary: ["can-spam-ai-messaging", "outbound-deliverability-risk", "needs-fix"],
    relatedComparison: "quality-gate-vs-deliverability-tooling",
    relatedIntegrations: ["lemlist", "smartlead"],
  },

  // ── Revenue Intelligence ────────────────────────────────────────
  "gong": {
    toolName: "Gong",
    category: "Intent & Enrichment",
    metaTitle: "Bookbag + Gong Compatibility | Bookbag Intelligence",
    metaDescription: "Use Gong conversation insights alongside Bookbag's production gate. Improve AI outbound quality with revenue intelligence data.",
    subtitle: "Bookbag works alongside Gong's conversation intelligence. Use call insights to inform outbound quality rubrics and improve AI-generated messaging.",
    description: "Gong is a revenue intelligence platform that records and analyzes sales calls, meetings, and emails. It provides conversation insights, deal intelligence, and coaching recommendations based on real buyer interactions.",
    howItWorks: [
      { title: "Inform rubrics with Gong insights", description: "Use Gong's conversation data to identify what messaging resonates with buyers. Build Bookbag rubrics that enforce these winning patterns in AI-generated outbound." },
      { title: "Gate AI outbound with context", description: "When AI generates outbound referencing deal context or call outcomes, Bookbag verifies the accuracy of those references before the message ships." },
      { title: "Close the feedback loop", description: "Track which Bookbag-approved messages lead to Gong-recorded conversations. Use this data to continuously refine both your AI prompts and your quality rubrics." },
    ],
    benefits: [
      { title: "Evidence-based rubrics", description: "Instead of guessing what good outbound looks like, use Gong's data on what actually works in conversations to define your Bookbag quality standards." },
      { title: "Messaging consistency", description: "Ensure AI-generated outbound aligns with the messaging patterns that Gong shows are most effective in your recorded calls and meetings." },
      { title: "Deal context accuracy", description: "AI messages that reference previous interactions or deal status can be verified. Bookbag catches claims that do not match the actual conversation history." },
    ],
    faqs: [
      { question: "Does Bookbag pull data from Gong?", answer: "Bookbag does not have a direct data connection to Gong. The compatibility is workflow-based: use Gong insights to inform your Bookbag rubrics and quality standards." },
      { question: "How do Gong insights improve Bookbag rubrics?", answer: "Gong reveals what messaging works in real conversations. Use these patterns to build rubrics that Bookbag enforces on AI-generated outbound, ensuring alignment with proven approaches." },
      { question: "Can Bookbag review Gong-suggested email templates?", answer: "Yes. If you use Gong's recommendations to generate AI email templates, route those templates through Bookbag for quality review before deploying them in sequences." },
    ],
    relatedPersonas: ["revops", "sales-enablement"],
    relatedGlossary: ["rubric-versioning", "ai-message-quality", "annotator-calibration"],
    relatedComparison: "rewrite-workflow-vs-prompt-tweaks",
    relatedIntegrations: ["salesloft", "outreach"],
  },

  // ── Intent & Enrichment ─────────────────────────────────────────
  "6sense": {
    toolName: "6sense",
    category: "Intent & Enrichment",
    metaTitle: "Bookbag + 6sense Compatibility | Bookbag Intelligence",
    metaDescription: "Gate AI outbound triggered by 6sense intent signals through Bookbag. Ensure intent-driven messages are accurate and compliant.",
    subtitle: "Bookbag works alongside 6sense intent data. Gate AI-generated messages triggered by buying signals through human-authority review.",
    description: "6sense is an intent data and account-based marketing platform that identifies in-market accounts using predictive analytics and intent signals. It helps sales and marketing teams prioritize accounts showing buying behavior.",
    howItWorks: [
      { title: "Intent triggers AI outbound", description: "When 6sense identifies accounts showing buying intent, your team generates AI outbound targeting those accounts. Route those messages through Bookbag before sending." },
      { title: "Verify intent-based claims", description: "AI messages that reference buying signals, pain points, or account context can be reviewed by Bookbag for accuracy. Ensure claims about the prospect's situation are defensible." },
      { title: "Ship reviewed messages", description: "Approved messages reach high-intent accounts with confidence. Every message has a documented review verdict for audit and compliance purposes." },
    ],
    benefits: [
      { title: "Protect high-intent outreach", description: "6sense identifies your best opportunities. A bad AI message to a high-intent account is a costly mistake. Bookbag prevents this by reviewing every message." },
      { title: "Accurate intent references", description: "AI may over-claim knowledge of the prospect's intent or buying stage. Bookbag catches messaging that makes assumptions beyond what the data supports." },
      { title: "ABM quality at scale", description: "Intent-driven ABM campaigns require personalized, high-quality messaging. Bookbag ensures quality standards hold even as you scale account-based outreach." },
    ],
    faqs: [
      { question: "Does Bookbag connect to 6sense?", answer: "Bookbag does not have a direct 6sense integration. The workflow is: 6sense identifies intent, your team generates AI outbound, and Bookbag gates those messages before delivery." },
      { question: "Can Bookbag verify intent data accuracy?", answer: "Bookbag reviews the messaging, not the data source. Reviewers flag messages that make unsupported claims about the prospect's intent, buying stage, or needs." },
      { question: "Is this useful for 6sense orchestration workflows?", answer: "Yes. Any AI-generated messaging triggered by 6sense orchestration rules can be routed through Bookbag before reaching the recipient." },
    ],
    relatedPersonas: ["revops", "b2b-saas"],
    relatedGlossary: ["ai-brand-safety", "ai-production-gate", "audit-ready-review"],
    relatedComparison: "bookbag-vs-prompt-engineering",
    relatedIntegrations: ["clearbit", "zoominfo"],
  },

  // ── Data Sources ────────────────────────────────────────────────
  "clearbit": {
    toolName: "Clearbit",
    category: "Data Source",
    metaTitle: "Bookbag + Clearbit Compatibility | Bookbag Intelligence",
    metaDescription: "Gate AI outbound enriched by Clearbit data through Bookbag. Ensure data-driven personalization is accurate before sending.",
    subtitle: "Bookbag works alongside Clearbit-enriched data. Gate AI messages that use enrichment data through human-authority review before delivery.",
    description: "Clearbit is a B2B data enrichment platform that provides company and contact data for sales and marketing teams. It enriches CRM records with firmographic, technographic, and demographic attributes used for targeting and personalization.",
    howItWorks: [
      { title: "Clearbit enriches, AI personalizes", description: "Clearbit provides enrichment data that feeds AI personalization engines. When AI generates outbound using this data, route the messages through Bookbag." },
      { title: "Verify data usage in messages", description: "Bookbag reviewers check whether AI correctly used Clearbit enrichment data. Hallucinated company details, wrong industries, and incorrect titles get flagged." },
      { title: "Approve accurate outreach", description: "Only messages that accurately reference prospect data are approved. Corrections document exactly what the AI got wrong for training data export." },
    ],
    benefits: [
      { title: "Data accuracy verification", description: "AI sometimes misinterprets or hallucinates on top of enrichment data. Bookbag catches cases where AI-generated messages reference incorrect company attributes." },
      { title: "Enrichment ROI protection", description: "You pay for Clearbit data to improve personalization. Bookbag ensures AI actually uses that data correctly instead of generating plausible-sounding but inaccurate details." },
      { title: "Structured error tracking", description: "When Bookbag flags data misuse, you can track patterns. Identify which enrichment fields AI struggles with most and adjust your prompts or templates accordingly." },
    ],
    faqs: [
      { question: "Does Bookbag use Clearbit data directly?", answer: "No. Bookbag reviews the AI-generated message, not the underlying data. Reviewers flag messages where the AI appears to have used enrichment data incorrectly or fabricated details." },
      { question: "Can Bookbag catch when AI ignores Clearbit data?", answer: "If AI generates generic messaging instead of using available enrichment data, Bookbag reviewers can flag this as a personalization quality issue based on your rubric criteria." },
      { question: "Is this useful if we use Clearbit with HubSpot?", answer: "Yes. Regardless of where Clearbit data feeds into your stack, any AI-generated outbound that references enrichment data can be routed through Bookbag for review." },
    ],
    relatedPersonas: ["b2b-saas", "revops"],
    relatedGlossary: ["ai-hallucination-detection", "ai-message-quality", "taxonomy-config"],
    relatedComparison: "bookbag-vs-prompt-engineering",
    relatedIntegrations: ["zoominfo", "6sense"],
  },

  "zoominfo": {
    toolName: "ZoomInfo",
    category: "Data Source",
    metaTitle: "Bookbag + ZoomInfo Compatibility | Bookbag Intelligence",
    metaDescription: "Gate AI outbound powered by ZoomInfo data through Bookbag. Verify AI personalization accuracy before sending.",
    subtitle: "Bookbag works alongside ZoomInfo contact and company data. Gate AI-generated messages that use ZoomInfo data through human-authority review.",
    description: "ZoomInfo is a B2B contact and company data platform that provides detailed records on businesses and decision-makers. Sales teams use ZoomInfo for prospecting, enrichment, and building targeted outbound lists.",
    howItWorks: [
      { title: "ZoomInfo powers prospect data", description: "ZoomInfo provides the contact and company data that feeds your AI outbound. When AI generates personalized messages using this data, route them through Bookbag." },
      { title: "Review data accuracy in messages", description: "Bookbag evaluates whether AI correctly used ZoomInfo data in its personalization. Wrong titles, outdated company info, and fabricated details get flagged." },
      { title: "Send accurate outreach", description: "Approved messages go out with verified personalization. Corrections create training data that helps your AI use prospect data more accurately over time." },
    ],
    benefits: [
      { title: "Contact data accuracy", description: "ZoomInfo provides rich contact data, but AI can misuse it. Bookbag catches messages that reference wrong titles, departments, or responsibilities." },
      { title: "Company data verification", description: "AI may hallucinate or misinterpret company data from ZoomInfo. Bookbag reviewers flag incorrect revenue ranges, employee counts, or technology references." },
      { title: "Prospect experience protection", description: "Nothing undermines outbound faster than getting basic facts wrong. Bookbag ensures AI-generated personalization built on ZoomInfo data is accurate before the prospect sees it." },
    ],
    faqs: [
      { question: "Does Bookbag integrate with ZoomInfo?", answer: "Bookbag does not directly connect to ZoomInfo. The workflow is: ZoomInfo provides data, AI generates personalized outbound, and Bookbag reviews those messages for accuracy." },
      { question: "Can Bookbag catch outdated ZoomInfo data in messages?", answer: "Bookbag reviewers flag messages that reference details that appear incorrect or outdated. If the AI references a prospect's old title or former company, this gets caught in review." },
      { question: "Is this relevant for ZoomInfo Engage?", answer: "Yes. Any AI-generated outbound triggered by ZoomInfo Engage workflows can be routed through Bookbag for quality review before sending." },
    ],
    relatedPersonas: ["b2b-saas", "revops"],
    relatedGlossary: ["ai-hallucination-detection", "outbound-deliverability-risk", "ai-brand-safety"],
    relatedComparison: "bookbag-vs-manual-review",
    relatedIntegrations: ["clearbit", "apollo"],
  },

  // ── Email Coaching ──────────────────────────────────────────────
  "lavender": {
    toolName: "Lavender",
    category: "Email Coaching",
    metaTitle: "Bookbag + Lavender Compatibility | Bookbag Intelligence",
    metaDescription: "Combine Lavender's email coaching with Bookbag's production gate. Score and gate AI outbound for maximum quality.",
    subtitle: "Bookbag works alongside Lavender's email coaching. Use both tools to ensure AI-generated outbound is optimized and quality-gated before sending.",
    description: "Lavender is an AI email coaching platform that scores sales emails in real time and provides suggestions to improve reply rates. It analyzes subject lines, email body, and personalization to help reps write better outbound.",
    howItWorks: [
      { title: "Lavender coaches, Bookbag gates", description: "Lavender provides real-time email scoring and suggestions. Bookbag provides a production gate with human-authority verdicts. The two serve different quality functions." },
      { title: "Complementary quality layers", description: "Lavender optimizes for reply rates and readability. Bookbag reviews for factual accuracy, compliance, brand alignment, and hallucination detection — areas beyond scoring models." },
      { title: "Route AI content through both", description: "Use Lavender to optimize AI-generated email drafts, then route them through Bookbag's production gate for human-authority review before sending." },
    ],
    benefits: [
      { title: "Optimization plus oversight", description: "Lavender optimizes for engagement metrics. Bookbag provides compliance and accuracy review. Together, they cover both performance and safety." },
      { title: "Different quality dimensions", description: "Email scoring catches readability and formatting issues. Human review catches hallucinations, risky claims, and compliance violations that scoring models miss." },
      { title: "Audit trail that scoring lacks", description: "Lavender provides a score. Bookbag provides a documented verdict with reviewer identity, rubric citations, and evidence — the kind of proof enterprise buyers and regulators need." },
    ],
    faqs: [
      { question: "Does Bookbag replace Lavender?", answer: "No. Lavender and Bookbag serve different functions. Lavender optimizes emails for engagement. Bookbag provides human-authority quality gating for compliance, accuracy, and brand safety." },
      { question: "Should I use Lavender before or after Bookbag?", answer: "Use Lavender first to optimize the email for readability and reply rates. Then route the optimized version through Bookbag for human-authority review before sending." },
      { question: "Can Bookbag use Lavender scores in its review?", answer: "Bookbag does not directly ingest Lavender scores. However, you can include scoring data as context for Bookbag reviewers if you want them to consider engagement optimization alongside compliance review." },
    ],
    relatedPersonas: ["email-coaching-platforms", "sales-enablement"],
    relatedGlossary: ["ai-message-quality", "gold-standard-rewrites", "human-in-the-loop-ai"],
    relatedComparison: "rewrite-workflow-vs-prompt-tweaks",
    relatedIntegrations: ["copy-ai", "salesloft"],
  },

  "copy-ai": {
    toolName: "Copy.ai",
    category: "Email Coaching",
    metaTitle: "Bookbag + Copy.ai Compatibility | Bookbag Intelligence",
    metaDescription: "Gate AI-generated sales copy from Copy.ai through Bookbag. Add human-authority review to AI copywriting workflows.",
    subtitle: "Bookbag is compatible with AI-generated sales copy from Copy.ai. Route AI-written outbound content through human-authority review before deployment.",
    description: "Copy.ai is an AI copywriting platform that generates marketing and sales content including email copy, ad text, blog posts, and outbound messaging. Sales teams use it to accelerate content creation for outbound campaigns.",
    howItWorks: [
      { title: "Generate copy in Copy.ai", description: "Use Copy.ai to generate sales email templates, outbound sequences, and personalized messaging. Export the AI-generated content for Bookbag review." },
      { title: "Gate through Bookbag", description: "Route Copy.ai outputs through Bookbag's production gate. Each piece of content receives a verdict based on your rubrics for accuracy, compliance, tone, and brand alignment." },
      { title: "Deploy reviewed content", description: "Approved content is ready for your outbound workflows. Import into your sequencing or sending platform knowing every message passed human-authority review." },
    ],
    benefits: [
      { title: "Brand voice consistency", description: "Copy.ai generates content fast, but style can vary between outputs. Bookbag ensures every piece of outbound copy meets your brand voice and messaging standards." },
      { title: "Claim verification", description: "AI copywriting tools sometimes generate unsupported product claims or competitive comparisons. Bookbag catches these before they reach prospects." },
      { title: "Template library building", description: "Reviewed and approved Copy.ai outputs build a library of vetted sales messaging. Reuse these templates with confidence that they meet your quality standards." },
    ],
    faqs: [
      { question: "Does Bookbag integrate with Copy.ai?", answer: "Bookbag is compatible with Copy.ai outputs. Generate content in Copy.ai, then route it through Bookbag via batch upload or API for review. A direct integration is planned." },
      { question: "Can Bookbag review Copy.ai workflow outputs?", answer: "Yes. Any text-based content generated by Copy.ai — including email copy, sequences, subject lines, and outbound templates — can be routed through Bookbag's production gate." },
      { question: "Is this overkill for simple email templates?", answer: "Even simple templates benefit from review. AI can introduce factual errors, compliance issues, or off-brand language in any output. Bookbag ensures everything that ships meets your standards." },
    ],
    relatedPersonas: ["sales-enablement", "b2b-saas"],
    relatedGlossary: ["ai-brand-safety", "gold-standard-rewrites", "sft-export"],
    relatedComparison: "bookbag-vs-prompt-engineering",
    relatedIntegrations: ["lavender", "regie-ai"],
  },
}

export function getIntegration(slug) {
  return integrations[slug] || null
}

export function getAllIntegrationSlugs() {
  return Object.keys(integrations)
}
